### ISSUE TITLE
I keep getting 50mb error logs 

### ISSUE THREAD

**Issue by Deven95** [peace-maker/smrpg#10]
Displaying call stack trace for plugin "smrpg_effects.smx":
L 01/24/2015 - 00:35:13: [SM]   [0]  Line 36, smrpg_effects/ignite.sp::ResetIgniteClient()
L 01/24/2015 - 00:35:13: [SM]   [1]  Line 87, E:\CSTRIKE\cstrike\addons\sourcemod\scripting\smrpg_effects.sp::Event_OnPlayerSpawn()
L 01/24/2015 - 00:35:21: [SM] Native "TriggerTimer" reported: Invalid timer handle 6c920591 (error 1)

Did i do something wrong?

**Comment by peace-maker** [comment]
Has it been some other plugin causing problems?
