### ISSUE TITLE
compiled but not working

### ISSUE THREAD

**Issue by ngx3** [peace-maker/smrpg#100]
I compiled the following, yet there is only settings, commands, reset. No options for upgrades?
smrpg
smrpg_antisuicide
smrpg_chatxpstats
smrpg_commandlist
smrpg_cstrike
smrpg_disablexp
smrpg_effects
smrpg_gifting
smrpg_import_thcrpg
smrpg_keyhint_info
smrpg_resetstats
smrpg_turbomode

Running CS:GO sourcemod ver 1.7.3-2597

**Comment by peace-maker** [comment]
As the install instructions say, you have to compile all the upgrades you want and put them on your server. They are in the scripting/upgrades folder and are separate plugins each.
