### ISSUE TITLE
RPG upgrades not working & database question

### ISSUE THREAD

**Issue by inputuserhere** [peace-maker/smrpg#102]
The rpg menu items are not working, I tried moving them from scripting/upgrades to /scripting no luck :( Any ideas?

One question I created a mysql database through my webhost, does it need a password and user? It's not saving my players upgrades/stats.

```
    "smrpg"
    {
        "driver"            "mysql"
        "database"          "gswebserv_smrpg"
    }
```

**Comment by Hetachi** [comment]
I don't want to be rude, but seriously?
You are lacking 3 things:

No ip/host
No username for database
No Password

There should be a template:
	"smrpg"
	{
		"driver"			"mysql"
		"host"				"ip address"
		"database"			"database name"
		"user"				"username"
		"pass"				"password"
		//"timeout"			"0" // Don't touch this you, since you don't know what it does.
		//"port"			"0" // Don't touch this you, since you don't know what it does.
	}

**Comment by inputuserhere** [comment]
I have all the .sp files from  scripting/upgrades to /scripting and .smx in /plugins folder. The menu comes up and you're able to pick upgrades, but they don't work.

**Comment by peace-maker** [comment]
Any errors in the sourcemod logs?

**Comment by Hetachi** [comment]
I think that he doesn't have the upgrade in right plugins folder
