### ISSUE TITLE
Edit CFG! HELP!

### ISSUE THREAD

**Issue by xanderc5** [peace-maker/smrpg#105]
I was just wondering, how do I edit how much XP and credits I get from leveling up, or something like that. Which file do I edit?

**Comment by coty9090** [comment]
cfg/sourcemod/plugin.smrpg.cfg and others like it in that subfolder.

**Comment by peace-maker** [comment]
Thanks @coty9090 

Hope you're good @xanderc5 
This bug tracker really isn't a help desk :(

**Comment by xanderc5** [comment]
Thank you guy. :D

**Comment by xanderc5** [comment]
guys

**Comment by xanderc5** [comment]
But I didn't find any .cfg folder

**Comment by xanderc5** [comment]
ok fixed

**Comment by peace-maker** [comment]
They are generated when you first load the plugin.
