### ISSUE TITLE
cannot read from file: "smlib"

### ISSUE THREAD

**Issue by razqed** [peace-maker/smrpg#107]
So when trying to compile the 'smrpg.sp' i get this error:
         **fatal error 182: cannot read from file: "smlib"**
Yet i have included both smlib.inc and the smlib folder, inside the "scripting\include" folder.

I have no clue on what to do?

**Comment by Nobody-x** [comment]
You need to download the smlib inc file and put it in your
scripting/include folder

**Comment by razqed** [comment]
I dont believe you read what i wrote, i already did what you just said. I pub smlib.inc inside scripting\include

**Comment by peace-maker** [comment]
Have you put it in the right folder? You have to put it in the include folder next to the spcomp executable you're using.

**Comment by razqed** [comment]
I put the compiler.exe and spcomp.exe inside the smrpg\scripting folder, now it gives me this error instead

"fatal error 182: cannot read from file: "sourcemod"

**Comment by razqed** [comment]
Okay so i figured that i had to drag the sourcemod\scripting\include into the smrpg include folder
then it told me that i had to drag in the autoexec, so i did that as well, now it gave me 20 errors.

![20errors](https://cloud.githubusercontent.com/assets/6500136/13901528/25acbf30-ee27-11e5-82dd-6841ec5d32aa.PNG)

**Comment by peace-maker** [comment]
Make sure to use the latest smlib version from the git repository. Don't use the release package.

**Comment by razqed** [comment]
oh wow.... thanks a lot.
