### ISSUE TITLE
max level barrier?

### ISSUE THREAD

**Issue by razqed** [peace-maker/smrpg#109]
how come i cant change the max level barrier for some upgrades?

eg. health cant seem to go above level 16 max.. im editing the "smrpg_upgrade_health.cfg" under "cfg/sourcemod/smrpg"

**Comment by peace-maker** [comment]
There is a hardcoded limit in some upgrades to prevent admins from configuring the upgrade above sane values. It's kind of obsolete now that all upgrades have much more config options.

You can ignore that hardcoded limit by setting `smrpg_ignore_level_barrier` to 1 in your plugin.smrpg.cfg.
