### ISSUE TITLE
Server crashed - Invalid database handle

### ISSUE THREAD

**Issue by live4net** [peace-maker/smrpg#11]
Somtime when map is changing, server crash. I got in logs:

L 02/11/2015 - 00:28:17: SourceMod error session started
L 02/11/2015 - 00:28:17: Info (map "surf_ski_2_GO") (file "errors_20150211.log")
L 02/11/2015 - 00:28:17: [SM] Native "SQL_ExecuteTransaction" reported: Invalid database handle 0 (error: 4)
L 02/11/2015 - 00:28:17: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 02/11/2015 - 00:28:17: [SM]   [0]  Line 287, smrpg/smrpg_players.sp::SaveAllPlayers()
L 02/11/2015 - 00:28:17: [SM]   [1]  Line 382, smrpg.sp::OnMapEnd()
L 02/11/2015 - 00:28:17: Error log file session closed.
L 02/11/2015 - 04:47:04: SourceMod error session started
L 02/11/2015 - 04:47:04: Info (map "surf_ski_2_GO") (file "errors_20150211.log")
L 02/11/2015 - 04:47:04: [SM] Native "SQL_ExecuteTransaction" reported: Invalid database handle 0 (error: 4)
L 02/11/2015 - 04:47:04: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 02/11/2015 - 04:47:04: [SM]   [0]  Line 287, smrpg/smrpg_players.sp::SaveAllPlayers()
L 02/11/2015 - 04:47:04: [SM]   [1]  Line 382, smrpg.sp::OnMapEnd()
L 02/11/2015 - 04:47:04: Error log file session closed.
L 02/11/2015 - 12:44:27: SourceMod error session started
L 02/11/2015 - 12:44:27: Info (map "surf_ski_2_GO") (file "errors_20150211.log")
L 02/11/2015 - 12:44:27: [SM] Native "SQL_ExecuteTransaction" reported: Invalid database handle 0 (error: 4)
L 02/11/2015 - 12:44:27: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 02/11/2015 - 12:44:27: [SM]   [0]  Line 287, smrpg/smrpg_players.sp::SaveAllPlayers()
L 02/11/2015 - 12:44:27: [SM]   [1]  Line 382, smrpg.sp::OnMapEnd()
L 02/11/2015 - 12:44:27: Error log file session closed.
L 02/11/2015 - 13:26:01: SourceMod error session started
L 02/11/2015 - 13:26:01: Info (map "surf_ski_2_GO") (file "errors_20150211.log")
L 02/11/2015 - 13:26:01: [SM] Native "SQL_ExecuteTransaction" reported: Invalid database handle 0 (error: 4)
L 02/11/2015 - 13:26:01: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 02/11/2015 - 13:26:01: [SM]   [0]  Line 287, smrpg/smrpg_players.sp::SaveAllPlayers()
L 02/11/2015 - 13:26:01: [SM]   [1]  Line 382, smrpg.sp::OnMapEnd()
L 02/11/2015 - 13:26:01: Error log file session closed.

**Comment by peace-maker** [comment]
That error is fixed now, but it shouldn't crash your server, if the database is unavailable. Do you have a stack trace of the crash?
