### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by razqed** [peace-maker/smrpg#110]
My server crashes about every 2 minutes someone is playing on the server, this is taken from the sourcemod error logs:

 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_icenade.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_fnade.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_fpistol.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "rockthevote.smx": Could not find required plugin "mapchooser"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_firepistol.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_bouncybullets.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_antidote.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_speed.smx": Required extension "dhooks" file("dhooks.ext") not running
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_icestab.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:40:45: [SM] Unable to load plugin "smrpg_upgrade_impulse.smx": Could not find required plugin "smrpg_effects"
**L 03/20/2016 - 15:42:17: [smrpg.smx] Error executing query 2 of 8 queries: database or disk is full**
L 03/20/2016 - 15:42:30: SourceMod error session started
L 03/20/2016 - 15:42:30: Info (map "hoejhus9_csgo") (file "errors_20160320.log")
L 03/20/2016 - 15:42:30: [SM] Unable to load extension "dhooks.ext": /home/tcagame/guld68/11405/csgo/addons/sourcemod/extensions/dhooks.ext.so: cannot open shared object file: No such file or directory
L 03/20/2016 - 15:42:30: [SM] Unable to load plugin "smrpg_upgrade_icenade.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:42:30: [SM] Unable to load plugin "smrpg_upgrade_fnade.smx": Could not find required plugin "smrpg_effects"
L 03/20/2016 - 15:42:30: [SM] Unable to load plugin "smrpg_upgrade_fpistol.smx": Could not find required plugin "smrpg_effects"

**Comment by Nobody-x** [comment]
You need to compile and put smrpg_effect

**Comment by razqed** [comment]
Yeah but is that what is causing it to crash though?

**Comment by razqed** [comment]
So i fixed the smrpg_effects, but im still getting crashes... i believe it has something to do with this line:
"**03/20/2016 - 15:59:40: [smrpg.smx] Error executing query 2 of 8 queries: database or disk is full**"

peace-maker helperino pleaserino

**Comment by Nobody-x** [comment]
Are you using SQLite or MySQL ?

**Comment by razqed** [comment]
neither? i dont understand... please dont call me a retard lol im new

**Comment by peace-maker** [comment]
If you followed the install steps from the readme, you added a "smrpg" section to your databases.cfg using the "sqlite" driver. That will get you a `sourcemod/data/sqlite/smrpg.sq3` file on your gameserver, which is the database where the stats are saved.

I've never seen that error before, but it seems like your database file is corrupt. Maybe because your server crashed while the database was being written to. Try shutting down your server, delete that file and start it again. All player data will be lost, but it looks like you just installed it anyway and have nothing to lose yet :)

To find the cause of a crash, you should install the Accelerator sourcemod extension and post the link to the crash dump, if it still crashes with a fresh database.

**Comment by razqed** [comment]
yeah true i did do that with the database, and its crashing, i'll try reinstalling the entire server anyways, just made it

**Comment by razqed** [comment]
this is what its giving me

L 03/20/2016 - 21:09:07: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:07: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:07: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:16: Error log file session closed.
L 03/20/2016 - 21:09:16: SourceMod error session started
L 03/20/2016 - 21:09:16: Info (map "de_dust2") (file "errors_20160320.log")
L 03/20/2016 - 21:09:16: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:16: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:16: [admin-sql-prefetch.smx] Could not connect to database "default": [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:09:17: [admin-sql-threaded.smx] Failed to connect to database: [2002]: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
L 03/20/2016 - 21:11:47: [smrpg.smx] Error executing query 2 of 4 queries: database or disk is full
L 03/20/2016 - 21:12:01: SourceMod error session started
L 03/20/2016 - 21:12:01: Info (map "de_dust2") (file "errors_20160320.log")

obviously it has something to do with that MySQL, but to me i might aswell be looking at chinese, help?

**Comment by Nobody-x** [comment]
If you have a dedicated server with MySQL installed on it. Find the
mysqld.sock path in your my.cnf and then in root type ln -s <mysqld.sock
path> /tmp/mysqld.sock

**Comment by razqed** [comment]
what if i dont have a server with MySQL installed on it though?

**Comment by Nobody-x** [comment]
Then in driver use SQLite instead of MySQL

**Comment by razqed** [comment]
can you explain how to? i dont know how to :/
