### ISSUE TITLE
problem Upgrade longJump with bhop

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#112]
problem Upgrade longJump with bhop!!!
I can use bhop with long jump upgrate. Player jumps like a standart jump( with out upgrade)

**Comment by vBDSK** [comment]
Could you make longjump like a THC RPG long jump

**Comment by maxgraham** [comment]
try this https://forums.alliedmods.net/showthread.php?p=2248506

**Comment by goodtime753** [comment]
The problem is not solved :(

**Comment by vBDSK** [comment]
I use this plugin. And Bhop don't work
