### ISSUE TITLE
smrpg_upgrade_damage

### ISSUE THREAD

**Issue by m33w** [peace-maker/smrpg#114]
Hi, 

First thx for this awsome plugin. I need some help to reduc the damage. 

Follow are just with lvl 2 damage :

smrpg_damage_percent "0.01"

30.781070 1000.000000 0.307810
final damage: 31.088880

smrpg_damage_percent "0.000001"

32.966854 1000.000000 0.000032
final damage: 32.966888

smrpg_damage_percent "0.000000"
Nothing is displaying in my test. 

Can you help me to find a solution, to make the damage more "normal" 

Best regards

**Comment by peace-maker** [comment]
What values would you expect and consider "normal"?

**Comment by m33w** [comment]
Hey, 

Thank you for the reply. I woud like to have the damage less powerful, 
Actualy my players have lvl 2 damage and is look like immortal. 
Its for a zombie riot server.

Best regards peace-maker.

**Comment by peace-maker** [comment]
I don't see how 1 dmg point more would make a player look like he's immortal?
Are you sure you don't have other values in the [damage_weapons.cfg](https://github.com/peace-maker/smrpg/blob/master/configs/smrpg/damage_weapons.cfg)?

**Comment by m33w** [comment]
Hey, yes i let the file damage_weapons.cfg with only this:

`"DamagePlusWeapons"
{
}`

so the plugin smrpg_upgrade_damage.sp should use the smrpg_damage_percent and smrpg_damage_max cvars right?

Best regards peace-maker.

**Comment by m33w** [comment]
Peace-maker can you give me some help ? 
I dont found the solution ...

Best regards.

**Comment by peace-maker** [comment]
Yes, it uses the values of those convars.
