### ISSUE TITLE
Error with translation

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#116]
I understand that this restriction on the characters
How to remove this restriction and how to solve the problem?
![err](https://cloud.githubusercontent.com/assets/18263102/15578662/11641d52-236a-11e6-8522-bbfae9e7e2c9.png)

**Comment by peace-maker** [comment]
What menu is this screenshot from? Have you added your own russian translations? Mind sharing it for others as the present one is missing lots of phrases.

**Comment by goodtime753** [comment]
Yes. This is a translation for smrpg
How to increase the number of phrases?

**Comment by peace-maker** [comment]
Use the english smrpg.phrases.txt as reference. There are much more other files next to that in the translations folder that you could translate to russian as well.

Which menu is shown in the screenshot directly?

**Comment by goodtime753** [comment]
rpg - Serrings (6)
If I use "en" link to the Russification, then foreigners will not be able to play

**Comment by goodtime753** [comment]
Off-topic
How to make that "speed" has worked as a "pulse"
Speed slides at a stop and does not affect the "Gravity"

**Comment by peace-maker** [comment]
That's actually a limitation in the topmenu core extension. The display buffer is only 64 bytes long and doesn't handle utf8 chars. I'll see if we can increase the buffer size in sourcemod.

When you're done translating the plugin, i'd gladly put it in the repository.

**Comment by peace-maker** [comment]
Try a new SourceMod 1.9 snapshot which includes [this](https://github.com/alliedmodders/sourcemod/pull/520) change and see if it changed something.

**Comment by peace-maker** [comment]
I expect this to be fixed? I'd still like to see your updated russian translation in here :smiley: 
You can use this tool to make sure you get all phrases translated
http://translator.mitchdempsey.com/sourcemod_plugins/tagged/smrpg
