### ISSUE TITLE
Sm:rpg settings and upgrade lvls

### ISSUE THREAD

**Issue by Shiz162** [peace-maker/smrpg#117]
Hello i installed the sm:rpg yesterday and its working perfectly  but i dont know to change settings like the experience you earn for headshot or knife or how much start credits you get and what is max lvl for upgrades all that stuff. I tried to change it in the plugins and the cfgs but nothing is working please help me. 

Ps: i am looking for a perfect bhop with does not limit your speed with longjump and does not stutter when bhopping but is bhopping fluently

Thanks

**Comment by peace-maker** [comment]
You should never have to touch the plugin code to configure stuff. If you have to, leave a message and someone can add a config option for it.

Are you sure you changed the settings in `[mod]/cfg/sourcemod/plugin.smrpg.cfg`? Headshot bonus experience is done in the smrpg_cstrike plugin, so check that config file. Knife experience is set in the [addons/sourcemod/configs/smrpg/weapon_experience.cfg](https://github.com/peace-maker/smrpg/blob/master/configs/smrpg/weapon_experience.cfg). The upgrade config files are all in `[mod]/cfg/sourcemod/smrpg/smrpg_upgrade_*.cfg`

You need to reload the config file or change the map after making changes for them to apply.
