### ISSUE TITLE
Reset stat

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#118]
SM:RPG > WARNING! Your stats were reset on 2016-05-25.
How can i control resetting of rpg stat?
Cvars or what?

**Comment by peace-maker** [comment]
Stats reset is scheduled by the smrpg_resetstats plugin, so check its convars in `cfg/sourcemod/plugin.smrpg_resetstats.cfg`. If there is no other message after that telling the player that the whole server got reset, it wasn't done through a scheduled reset for all players but some admin ran smrpg_resetstats on the player. Check your sourcemod logs for lines like `X permanently reset all stats of player Y`.
