### ISSUE TITLE
Compiling a lot of the files have errors

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#12]
I must be missing a step or something...  I compiled the main plugin (smrpg.smx), and most of the optional features, but a lot of the other ones don't compile because of errors.

I  used CS:S,  windows stable  sourcemod 1.7.1-git5151 and  got the compile requirements...

smrpg_database.sp

<119> error 017: undefined symbol "LoadSettingsTable"
<123> error 017: undefined symbol "GetUpgradeCount"
and a few more in this one.

No files generate in /cfg/sourcemod/smrpg. (probably because i can't compile smrpg_upgrades.sp)

While using Shrinking, when you crouch in CS:S, it doesn't stay crouched. the screen shoots up as if you never crouched, and then when you release crouch it goes down (to where it should be) and comes up normally.

**Comment by peace-maker** [comment]
All files in the scripting/smrpg subfolder are included in the smrpg.sp. Don't try to compile them on their own.
Make sure your gameserver user has permissions to write in the /cfg/sourcemod/smrpg folder. It should create config files for each upgrade you load.
