### ISSUE TITLE
Langauge menu?

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#120]
Is this possible? A menu where players can choose their language for the rpg menu?

**Comment by peace-maker** [comment]
The plugin uses SourceMod's translation layer, which doesn't allow changing the language of each client per plugin. It could be possible with some nasty wrappers, but I'd rather not do something like that.

I'd recommend you to install some [language changer](https://forums.alliedmods.net/showthread.php?t=153145). This lets clients select any installed language which gets used for ALL messages they see from sourcemod - not only the ones from this plugin.
