### ISSUE TITLE
[Feature Request] Add max level info

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#124]
Add the maximum level of an upgrade to the upgrade menu (i.e: Resupply 5/10 [Cost: 30])

I wanted to request this because knowing what each skill max level is gives a better ideal strategy of what i would want to upgrade first or if i should start upgrading something else if maxing a certain skill would take too long.

**Comment by peace-maker** [comment]
Here's a new convar `smrpg_show_maxlevel_in_menu` for you.

**Comment by coty9090** [comment]
Awesome. Thanks!
