### ISSUE TITLE
[Request] Ice Stab damage reduction

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#126]
I want to request an Ice Stab damage reduction config. I saw you have a icestab limit dmg, but i want to suggest a config of whoever gets ice stabbed has weapon bullet dmg reduced by a certain %.

**Comment by peace-maker** [comment]
A config to set the damage percent for each weapon differently or just one convar value for all?

**Comment by coty9090** [comment]
I've always preferred there to be options for almost everything. Makes setting servers the way you want way easier.

**Comment by peace-maker** [comment]
There you go. Not just for the Ice Stab upgrade but to any other upgrade freezing some player.
Have a look at the freeze_limit_damage config.
