### ISSUE TITLE
Armor+ not going above 127 and bots earning exp hangs the server

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#13]
*EDIT*

Is there any way for Armor+ to go above 127?

Whenever the bots earn exp, it lags, hangs, or crashes the server.

**Comment by coty9090** [comment]
Got the rpg effects working... took a few tries for some reason.  i switched to a newly created config instead of just changing the config back to default. 

Clipsize seems to work for some players and not for others...

**Comment by coty9090** [comment]
Fixed all my issues... some reason it had personally disabled clipsize for some players individually....

**Comment by peace-maker** [comment]
The armor value is just a signed byte, so it can't be set higher than 127 or it would be -128. It's a restriction on the client and it's not possible to show higher numbers in the HUD.

Do you have a stack trace of such a crash? https://forums.alliedmods.net/showthread.php?t=146644

**Comment by coty9090** [comment]
I'm getting these errors in SM log.


L 03/03/2015 - 16:31:54: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 03/03/2015 - 16:31:54: [SM]   [0]  Line 879, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg.sp::IsValidPlugin()
L 03/03/2015 - 16:31:54: [SM]   [1]  Line 761, smrpg/smrpg_upgrades.sp::IsValidUpgrade()
L 03/03/2015 - 16:31:54: [SM]   [2]  Line 644, smrpg/smrpg_players.sp::BotPickUpgrade()
L 03/03/2015 - 16:31:54: [SM]   [3]  Line 209, smrpg/smrpg_stats.sp::Stats_PlayerNewLevel()
L 03/03/2015 - 16:31:54: [SM]   [4]  Line 309, smrpg/smrpg_stats.sp::Stats_AddExperience()
L 03/03/2015 - 16:31:54: [SM]   [5]  Line 534, smrpg/smrpg_stats.sp::Native_AddClientExperience()
L 03/03/2015 - 16:31:54: [SM] Plugin encountered error 30: Script execution timed out
L 03/03/2015 - 16:31:54: [SM] Native "SMRPG_AddClientExperience" reported: Error encountered while processing a dynamic native
L 03/03/2015 - 16:31:54: [SM] Displaying call stack trace for plugin "smrpg_cstrike.smx":
L 03/03/2015 - 16:31:54: [SM]   [0]  Line 490, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_cstrike.sp::Debug_AddClientExperience()
L 03/03/2015 - 16:31:54: [SM]   [1]  Line 314, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_cstrike.sp::Event_OnPlayerDeath()

**Comment by coty9090** [comment]
Alright, i lowered the settings in the config and skills for exp, level, etc. and it cleared the crashing for now, but it still hangs although not that often now. (once every few hrs, when before it did it every time a bot gained exp)

**Comment by peace-maker** [comment]
Try the latest version now. There were some flaws in the logic of bots picking upgrades. It didn't cover all the checks for buying upgrades that were added over time.

**Comment by coty9090** [comment]
lmao... i think that fixed it... I tried latest version and the bots level up and earn exp without the server crashing/hanging, but i guess i got to reconfigure the exp settings.... when they shot me and i shot them we all gained like 1 billion exp hahaha.... i'll let you know if my exp config is the problem.

**Comment by peace-maker** [comment]
> "Error executing query: disk I/O error"

is there space left on your hdd? Those are some weird errors unrelated to this plugin i guess.

**Comment by coty9090** [comment]
Well what error is making everyone gain insane amounts of exp?
