### ISSUE TITLE
smrpg_upgrade_ljump.sp

### ISSUE THREAD

**Issue by iNcyde** [peace-maker/smrpg#14]
Hello, i got problem with smrpg_upgrade_ljump.sp, i want to make this upgrade better but i dont know how :/ i want to jump like in THC RPG... boost on second jump was better than slow jumping like now (with  autobh). Can u help me fix this? Boost with autobh was rly epic.. now peaople cry :dancers:

**Comment by iNcyde** [comment]
(sorry for my low english) :+1:

**Comment by peace-maker** [comment]
Just configure it to have the same boost for the first jump as the following.
smrpg_ljump_incstart and smrpg_ljump_inc
