### ISSUE TITLE
Max Level Change?

### ISSUE THREAD

**Issue by kieeranxd** [peace-maker/smrpg#15]
I'm really sorry for commenting here but I couldn't find the thread on AlliedModders. I was wondering, is it possible to change the max level from level 33? If so, in which file would I do that because I can't seem to find it anywhere.

**Comment by peace-maker** [comment]
Which maxlevel? There's no cap at 33 unless you set it so using the convars.

**Comment by peace-maker** [comment]
I guess this was a false alarm.
