### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by Rownan** [peace-maker/smrpg#16]
I am trying to compile the core smrpg.sp file and I am getting 19 warnings,

> **smrpg_database.sp(328)**
warning 213: tag mismatch
**smrpg_database.sp(330)**
warning 213: tag mismatch
**smrpg_database.sp(331)**
warning 213: tag mismatch
**smrpg_database.sp(350)**
warning 213: tag mismatch
**smrpg_database.sp(352)**
warning 213: tag mismatch
**smrpg_database.sp(353)**
warning 213: tag mismatch
**smrpg_database.sp(466)**
warning 213: tag mismatch
**smrpg_database.sp(469)**
warning 213: tag mismatch
**smrpg_database.sp(472)**
warning 213: tag mismatch
**smrpg_admincommands.sp(50)**
warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthID
**smrpg_admincommands.sp(909)**
warning 213: tag mismatch
**smrpg_admincommands.sp(911)**
warning 213: tag mismatch
**smrpg_admincommands.sp(912)**
warning 213: tag mismatch
**smrpg_admincommands.sp(1005)**
warning 213: tag mismatch
**smrpg_admincommands.sp(1008)**
warning 213: tag mismatch
**smrpg_admincommands.sp(1171)**
warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthID

**Comment by Bara20** [comment]
Try with SourceMod 1.6.

**Comment by Rownan** [comment]
Fixed the problem, thank you very much Bara.
