### ISSUE TITLE
[Upgrade Request] Equipment Stealth - Scrapped

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#171]
Equipment Stealth - Makes equipment less visible (guns, nades, bomb, defuse kit, etc. (Doesn't work for stuff dropped on the ground) - lvl 1 95% visible - lvl 2 90%

**Comment by peace-maker** [comment]
That's not possible. The bomb, nades, defuser and other not-active weapon on the players back are drawn client side based on a bit field. So you can only hide them completely but can't change the alpha individually.

Sad the game client doesn't apply the same alpha value as the player has..

**Comment by coty9090** [comment]
ah... that sucks! guess this one's scrapped too. haha
