### ISSUE TITLE
PLugin unable to load

### ISSUE THREAD

**Issue by nguyenbaodanh** [peace-maker/smrpg#18]
[SM] Unable to load plugin "smrpg_keyhint_info.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_disablexp.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_commandlist.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_chatxpstats.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_turbomode.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_gifting.smx": Could not find required plugin "smrpg"
14:24:26 L 03/15/2015 - 14:23:35: [SM] Unable to load plugin "smrpg_antisuicide.smx": Could not find required plugin "smrpg"

What did I missing ? :(

**Comment by kieeranxd** [comment]
You need to compile the .sp files first

**Comment by peace-maker** [comment]
The core "smrpg.smx" plugin is not running and you didn't paste the error why it isn't.

**Comment by nguyenbaodanh** [comment]
Fixed.
does the keyhint still causing crash ? And i see there is a effects folder anh files like fire freeze but I can't compile them. 
Do I need to combine them like the upgrades ?

**Comment by nguyenbaodanh** [comment]
Oh sry i mean compile not combine

**Comment by nguyenbaodanh** [comment]
97 Disabled: "SM:RPG Upgrade > Stealth" (1.0) by Jannik "Peace-Maker" Hartung
           98 Disabled: "SM:RPG Upgrade > Fast Reload" (1.0) by Peace-Maker
           99 Disabled: "SM:RPG Upgrade > Poison Smoke" (1.0) by Jannik "Peace-Maker" Hartung
           100 <Bad Load> sm_buy_respawn.smx
           101 "Round Money" (PLUGIN_VERSION) by LIONz
           102 Disabled: "SM:RPG Upgrade > Shrinking" (1.0) by Peace-Maker

Why are these disabled ?

**Comment by peace-maker** [comment]
They aren't supported on csgo.
