### ISSUE TITLE
Enhancement: HP Regeneration configurable

### ISSUE THREAD

**Issue by beastlypro** [peace-maker/smrpg#20]
I've used HP regeneration plugins before, and they let you assign time and amount of health as part of their settings. I thought, if you were able to do something like that here, it'd be great.

Ideally, you can set these:

Starting time between regeneration iterations. (Preferably this value and timed reduced per level can be set by seconds, but can be set with decimals as well, to have say.. 0.5 of a second)
Time reduced per level.
Health gained per iteration.

**Comment by coty9090** [comment]
That should go for armor regen as well...

**Comment by peace-maker** [comment]
Added a few new convars for the hp and armor regen upgrades. Thanks for the suggestion:)
smrpg_regen_amount, smrpg_regen_amount_inc, smrpg_regen_interval and smrpg_regen_interval_dec.

The default values are set to replicate the previous behavior.
