### ISSUE TITLE
smrpg_addlvl steamid ?

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#215]
What does the steamid mean and which one you mean by it? Is it 32 or 64 ?
And how would it be written correctly?

smrpg_addlvl "STEAM_0:1:98661890" "1"
or without the "" marks ?

**Comment by peace-maker** [comment]
It uses SourceMod's API to find the connected player by userid, name or steamid. SourceMod transparently handles all kinds of steamid formats. You have to include the quotes "" or else the steamid might get splitted by the ":" or something.

The command, as well as all the other admin commands, only work on connected clients yet btw.

**Comment by Hetachi** [comment]
If it's executed on join would that work?

**Comment by peace-maker** [comment]
Do you execute it while you're on the server? What is the message printed to the console when you're executing the command? Try `smrpg_addlvl "STEAM_0:1:98661890" 1` so the `1` with no quotes.

> If it's executed on join would that work?

You have to execute it after the player authenticated with steam, so after OnClientAuthorized is called.

**Comment by Hetachi** [comment]
```
os      :  Linux
type    :  community dedicated
map     : surf_exile_2016_mar
players : 9 humans, 0 bots (22/0 max) (not hibernating)

# userid name uniqueid connected ping loss state rate
# 315 1 "LikkeY" STEAM_1:1:98035822 46:59 65 0 active 80000
# 316 2 "Ranetin" STEAM_1:1:83857013 46:13 121 0 active 80000
# 318 3 "papa gaben" STEAM_1:1:114892609 27:10 51 0 active 80000
# 322 4 "★Chilly" STEAM_1:0:76137753 14:54 65 0 active 128000
# 324 5 "Hetachi" STEAM_1:1:98661890 00:33 37 0 active 80000
# 321 6 "Töhö" STEAM_1:0:59490946 19:29 115 0 active 80000
# 323 7 "NitroExpr3ss" STEAM_1:0:78810762 06:12 129 0 active 80000
# 325 8 "Patric" STEAM_1:1:64502743 00:23 150 78 spawning 80000
# 326 9 "veggiX" STEAM_1:0:175713528 00:00 71 43 spawning 80000
#end
Patric connected.
] smrpg_addlvl "STEAM_0:1:98661890" 1
[SM] No matching client was found.
```

**Comment by peace-maker** [comment]
Reading [the wiki](https://wiki.alliedmods.net/Admin_Commands_(SourceMod)#How_to_Target) helps :o
You have to add a # before the steamid and make sure you use the correct `STEAM_0` or `STEAM_1` prefix your game uses (or used to use).
`smrpg_addlvl "#STEAM_1:1:98661890" 1`

**Comment by Hetachi** [comment]
Awesome thank you for this!
