### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by downwardlymobile** [peace-maker/smrpg#217]
Hi there =) Thank you for your hard work on this plugin I have enjoyed it for a while. I am trying to install it on my server. I had clicked the "clone or download" button, saved it and uploaded it to my server in the sourcemod directory. When starting it, smrpg was not running though my other plugins are.

Should I be compiling this? I have never needed to before, so if so can you briefly tell me how to? Thanks again!

**Comment by Hetachi** [comment]
https://github.com/peace-maker/smrpg#compile-requirements

**Comment by peace-maker** [comment]
Have a look at #78 and all the other linked issues there.
