### ISSUE TITLE
effect are not working

### ISSUE THREAD

**Issue by johank20** [peace-maker/smrpg#218]
i have compile everything but when i upgrade in game i wont make a effect

**Comment by Hetachi** [comment]
Paste your log file, you 100% have something in there.

**Comment by johank20** [comment]
L 09/05/2016 - 19:05:27: SourceMod error session started
L 09/05/2016 - 19:05:27: Info (map "hoejhus_big_v2") (file "errors_20160905.log")
L 09/05/2016 - 19:05:27: [SM] Detected parse error(s) in file "D:\UserFiles\HAMZAA\GameServers\TC35118800621750458021778\csgo\addons\sourcemod\configs\databases.cfg"
L 09/05/2016 - 19:05:27: [SM] Line 1: Line contained too many invalid tokens
L 09/05/2016 - 19:05:28: [SM] Unable to load extension "clientprefs.ext": Could not find any suitable database configs
L 09/05/2016 - 19:05:28: [SM] Unable to load extension "dhooks.ext": The specified module could not be found.


L 09/05/2016 - 19:05:28: [SM] Native "SQL_FastQuery" reported: Invalid database Handle 0 (error: 4)
L 09/05/2016 - 19:05:28: [SM] Displaying call stack trace for plugin "simplecsgoranks.smx":
L 09/05/2016 - 19:05:28: [SM]   [0]  Line 573, simplecsgoranks.sp::newDB()
L 09/05/2016 - 19:05:28: [SM]   [1]  Line 902, simplecsgoranks.sp::OnPluginStart()
L 09/05/2016 - 19:05:28: [smrpg.smx] Error connecting to database (reconnecting in 360 seconds): Could not find database conf "default"
L 09/05/2016 - 19:05:28: [SM] Unable to load plugin "smrpg_upgrade_grenaderesup_cstrike.smx": Native "DataPack.DataPack" was not found
L 09/05/2016 - 19:05:28: [SM] Unable to load plugin "smrpg_upgrade_speed.smx": Required extension "dhooks" file("dhooks.ext") not running
L 09/05/2016 - 19:05:28: [SM] Native "SQL_GetError" reported: Invalid statement or db Handle 0 (error: 4)
L 09/05/2016 - 19:05:28: [SM] Displaying call stack trace for plugin "srank.smx":
L 09/05/2016 - 19:05:28: [SM]   [0]  Line 15, ShadowLibs/srank_mysql.sp::RunDataBaseSetUp()
L 09/05/2016 - 19:05:28: [SM]   [1]  Line 9, C:\Users\Laurence\Documents\Laurence\Work Area\Sourcemod\Studio\Plugins\CSGO-SRank\addons\sourcemod\scripting\srank.sp::OnPluginStart()
L 09/05/2016 - 19:05:28: [SM] Plugin encountered error 25: Call was aborted
L 09/05/2016 - 19:05:28: [SM] Native "SetFailState" reported: Can't find subkey in configuration file addons\sourcemod\configs\TheEdgeClanTags.cfg!
L 09/05/2016 - 19:05:28: [SM] Displaying call stack trace for plugin "TheEdgeclanTags.smx":
L 09/05/2016 - 19:05:28: [SM]   [0]  Line 139, plugin.sp::LoadCfgTags()
L 09/05/2016 - 19:05:28: [SM]   [1]  Line 64, plugin.sp::OnPluginStart()

**Comment by Hetachi** [comment]
You have not configured database.cfg file correctly.
You have not installed dhooks.

Those are the first 2 things you probably should do before even trying to run anything, is to configure it correctly.

**Comment by peace-maker** [comment]
Have you managed to work it out by adding an entry to the databases.cfg?
Can you paste your full log? It should still work temporaly - just not saving the stats.
