### ISSUE TITLE
Lvl up too fast ! How to set the exp require ?

### ISSUE THREAD

**Issue by nguyenbaodanh** [peace-maker/smrpg#22]
Hello. I'm new to this, and I don't know how to set the lvl exp point required to each level. Are these ?

// Maximum experience that will ever be required
// -
// Default: "50000"
// Minimum: "0.000000"
smrpg_exp_max "50000"

// Experience required for Level 1
// -
// Default: "250"
// Minimum: "0.000000"
smrpg_exp_start "100"

// Increment experience required for each level (until smrpg_exp_max)
// -
// Default: "50"
// Minimum: "0.000000"
smrpg_exp_inc "5000"

**Comment by peace-maker** [comment]
Those are the correct convars, but you should approach it from the other side. Change how much experience players get for their actions like killing or hurting others and lower those rates.
