### ISSUE TITLE
[Upgrade] Denial don't work

### ISSUE THREAD

**Issue by piotrekkrol7** [peace-maker/smrpg#225]
Hi mate , the upgrade DENIAL is not working , and when you drop a weapon it disappearing it is not visible on the floor ,and in Denial when the round is over u have no gun , its not saving it to equip

**Comment by peace-maker** [comment]
You must be running some other plugin or setting for the weapons to disappear when dropped. smrpg doesn't have any code that removes dropped weapons.

Denial works by saving which weapons you had when you died and give them back in the next round. It doesn't jump in if you survived the last round or dropped your weapon before dying.

**Comment by piotrekkrol7** [comment]
yeah but when i die i don't have weapons :+1:

**Comment by piotrekkrol7** [comment]
can you repear denial but this don't work

**Comment by piotrekkrol7** [comment]
@peace-maker  look on this https://www.youtube.com/watch?v=_0B4bvQtEMI&feature=youtu.be

**Comment by peace-maker** [comment]
Does that stop when not having the denial upgrade active?
