### ISSUE TITLE
Cant compile the plugin 

### ISSUE THREAD

**Issue by brushu** [peace-maker/smrpg#226]
Some of the files are unable to compile with the newest stable sourcemod version : 

eG.: 

smrpg_admincommands.sp(43) : error 017: undefined symbol "ShowRPGAdminMenu"
smrpg_admincommands.sp(61) : error 017: undefined symbol "PlayerInfo"
smrpg_admincommands.sp(61) : error 009: invalid array size (negative, zero or ou                                                                                                                                                             t of bounds)
smrpg_admincommands.sp(61) : error 036: empty statement
smrpg_admincommands.sp(61) : fatal error 190: too many error messages on one lin                                                                                                                                                             e

Compilation aborted.
5 Errors.

**Comment by peace-maker** [comment]
Just compile the smrpg.sp. It includes all the files in the scripting/smrpg subfolder, so don't try to compile them on their own.
