### ISSUE TITLE
server crash due...

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#227]
Log:
[SM] Exception reported: Invalid field "hints" for message "CCSUsrMsg_KeyHintText"
[SM] Blaming: smrpg/smrpg_keyhint_info.smx
[SM] Call stack trace:
[SM]   [0] PbSetString
[SM]   [1] Line 1786, C:\Users\goodt\Desktop\addons\sourcemod\scripting\include\smlib/clients.inc::Client_PrintKeyHintText
L 10/16/2016 - 17:23:36: [SM]   [2] Line 296, smrpg_keyhint_info.sp::TopMenu_SettingsItemHandler

What is the problem, how to fix?

**Comment by goodtime753** [comment]
[SM] Exception reported: Client index 97 is invalid (arg 5)
[SM] Blaming: smrpg/smrpg_keyhint_info.smx
[SM] Call stack trace:
[SM]   [0] Format
[SM]   [1] Line 150, smrpg_keyhint_info.sp::Timer_ShowInfoPanel

that's more errors..

**Comment by peace-maker** [comment]
I forgot to change another call to KeyHint in the first error, but looks like smlib was using the wrong API for that usermessage. https://github.com/bcserv/smlib/commit/94d9211b6bf02129614d074f30f5c741cf28e77b

The second one is interesting. A player seems to be in in-eye or thirdperson spectator mode, but not spectating a target.

**Comment by Nobody-x** [comment]
For the spectator, maybe on the spectate camera when you join a map.

**Comment by Denis-Raev** [comment]
Error: https://forums.alliedmods.net/showthread.php?p=2464044#post2464044

**Comment by peace-maker** [comment]
As posted in your topic, you need to get the latest smlib version. https://github.com/bcserv/smlib
