### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by AllLuckNoSkill** [peace-maker/smrpg#229]
I have downloaded everything need and followed the instructions right and i get this. Please Help
Edit:
when i pasted it, it does not show the start. after the number it says "Failed" in front of all of them.

 17 <Failed> "SM:RPG > Anti-Selfkill" (1.0) by Peace-Maker
  18 <Failed> "SM:RPG > Chat Experience Stats" (1.0) by Jannik "Peace-Maker" Hartung
  19 <Failed> "SM:RPG > Command List" (1.0) by Jannik "Peace-Maker" Hartung
  20 "SM:RPG > Effect Hub" (1.0) by Peace-Maker
  21 <Failed> "SM:RPG > Credit Gifting" (1.0) by Peace-Maker
  22 <Failed> "SM:RPG > Key Hint Infopanel" (1.0) by Jannik "Peace-Maker" Hartung
  23 <Failed> "SM:RPG > Turbo Mode" (1.0) by Jannik "Peace-Maker" Hartung
  24 <Failed> "SM:RPG Upgrade > Antidote" (1.0) by Peace-Maker
  25 <Failed> "SM:RPG Upgrade > Armor Helmet" (1.0) by Peace-Maker
  26 <Failed> "SM:RPG Upgrade > Armor+" (1.0) by Jannik "Peace-Maker" Hartung
  27 <Failed> "SM:RPG Upgrade > Armor regeneration" (1.0) by Jannik "Peace-Maker" Hartung
  28 <Failed> "SM:RPG Upgrade > Bouncy Bullets" (1.0) by Peace-Maker
  29 <Failed> "SM:RPG Upgrade > Increase Clipsize" (1.0) by Peace-Maker
  30 <Failed> "SM:RPG Upgrade > Damage+" (1.0) by Jannik "Peace-Maker" Hartung
  31 <Failed> "SM:RPG Upgrade > Denial" (1.0) by Jannik "Peace-Maker" Hartung
  32 <Failed> "SM:RPG Upgrade > Reduced Fall Damage" (1.0) by Peace-Maker
  33 Disabled: "SM:RPG Upgrade > Fast Reload" (1.0) by Peace-Maker
  34 <Failed> "SM:RPG Upgrade > Fire Pistol" (1.0) by Jannik "Peace-Maker" Hartung
  35 <Failed> "SM:RPG Upgrade > Firerate" (1.0) by Peace-Maker
  36 <Failed> "SM:RPG Upgrade > Fire Grenade" (1.0) by Jannik "Peace-Maker" Hartung
  37 <Failed> "SM:RPG Upgrade > Frost Pistol" (1.0) by Jannik "Peace-Maker" Hartung
  38 <Failed> "SM:RPG Upgrade > Reduced Gravity" (1.0) by Jannik "Peace-Maker" Hartung
  39 <Failed> "SM:RPG Upgrade > Grenade Resupply" (1.0) by Jannik "Peace-Maker" Hartung
  40 <Failed> "SM:RPG Upgrade > Health+" (1.0) by Jannik "Peace-Maker" Hartung
  41 <Failed> "SM:RPG Upgrade > Ice Grenade" (1.0) by Peace-Maker
  42 <Failed> "SM:RPG Upgrade > Ice Stab" (1.0) by Jannik "Peace-Maker" Hartung
  43 <Failed> "SM:RPG Upgrade > Impulse" (1.0) by Jannik "Peace-Maker" Hartung
  44 <Failed> "SM:RPG Upgrade > Long Jump" (1.0) by Jannik "Peace-Maker" Hartung
  45 <Failed> "SM:RPG Upgrade > Medic" (1.0) by Jannik "Peace-Maker" Hartung
  46 Disabled: "SM:RPG Upgrade > Poison Smoke" (1.0) by Jannik "Peace-Maker" Hartung
  47 <Failed> "SM:RPG Upgrade > Health regeneration" (1.0) by Jannik "Peace-Maker" Hartung
  48 <Failed> "SM:RPG Upgrade > Resupply" (1.0) by Jannik "Peace-Maker" Hartung
  49 Disabled: "SM:RPG Upgrade > Shrinking" (1.0) by Peace-Maker
  50 <Failed> "SM:RPG Upgrade > Stealth" (1.0) by Jannik "Peace-Maker" Hartung
  51 <Failed> "SM:RPG Upgrade > Vampire" (1.0) by Jannik "Peace-Maker" Hartung

**Comment by Nobody-x** [comment]
Can you paste your log ?

**Comment by AllLuckNoSkill** [comment]
Is this what you're wanting?


L 10/21/2016 - 15:49:39: [SM] Failed to load plugin "smrpg_upgrade_fastreload.css.smx": This plugin is for CS:S only..
L 10/21/2016 - 15:49:39: [SM] Failed to load plugin "smrpg_upgrade_poisonsmoke.cstrike.smx": This plugin is for use in Counter-Strike games only. Bad engine version 12..
L 10/21/2016 - 15:49:39: [SM] Failed to load plugin "smrpg_upgrade_shrinking.smx": CS:GO models don't support scaling properly :(.
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'teamplay_restart_round' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_antisuicide.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_chatxpstats.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_commandlist.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_gifting.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_keyhint_info.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_turbomode.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_antidote.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_armorhelmet_cstrike.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_armorplus_cstrike.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_armorregen_cstrike.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_bouncybullets.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_clipsize.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_damage.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_denial.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_falldamage.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_firepistol.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_firerate.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_fnade.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_fpistol.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_gravity.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_grenaderesup_cstrike.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_health.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_icenade.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_icestab.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_impulse.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_ljump.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_medic.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_regen.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_resup.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_stealth.smx": Could not find required plugin "smrpg"
L 10/21/2016 - 15:49:39: [SM] Unable to load plugin "smrpg_upgrade_vampire.smx": Could not find required plugin "smrpg"

**Comment by Nobody-x** [comment]
On which game are you ?

You're trying to install these plugins, but you can't : 
`smrpg_upgrade_fastreload.css.smx`
`smrpg_upgrade_poisonsmoke.cstrike.smx`
`smrpg_upgrade_shrinking.smx`

Remove them from the plugins folder.

Then copy log from the first one error (you can use [PasteBin](http://pastebin.com/index))

It's sound like the smrpg.smx can't load :
[Check all installation steps here](https://github.com/peace-maker/smrpg#installation) and verify that you don't forget something like creating the database entry, or installing DHook extension.

**Comment by AllLuckNoSkill** [comment]
i have removed the files from 
\csgo\addons\sourcemod\plugins
and its still not working, i have copyed everything so you can see everything

http://pastebin.com/5YnnCcJZ

**Comment by peace-maker** [comment]
Do you have a smrpg.smx in your plugins folder?

**Comment by Nobody-x** [comment]
If you have smrpg.smx in your folder, show us the last log from `\csgo\addons\sourcemod\logs\`

**Comment by AllLuckNoSkill** [comment]
i do not have smrpg.smx in my plugins folder, and when i try to compile it it comes up with
//// smrpg.sp
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(46) : error 001: expected token: ";", but found "-identifier-"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(47) : error 021: symbol already defined: "char"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(48) : error 021: symbol already defined: "char"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(50) : error 001: expected token: ";", but found "-identifier-"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(51) : error 001: expected token: ";", but found "-identifier-"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(53) : error 021: symbol already defined: "bool"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(54) : error 021: symbol already defined: "Handle"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(59) : error 001: expected token: ";", but found "-identifier-"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(59) : error 010: invalid function or declaration
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(60) : error 021: symbol already defined: "int"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(60) : error 010: invalid function or declaration
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(70) : error 021: symbol already defined: "int"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(84) : error 021: symbol already defined: "int"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(96) : error 001: expected token: ";", but found "-identifier-"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(96) : error 017: undefined symbol "create"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(96) : error 021: symbol already defined: "bool"
// C:\Stuff\Servers\CSGO\TEST\csgo\addons\sourcemod\scripting\include\autoexecconfig.inc(96 -- 107) : fatal error 127: too many error messages on one line
//
// Compilation aborted.
// 17 Errors.
//
// Compilation Time: 2.3 sec
// ----------------------------------------

Press enter to exit ...

**Comment by peace-maker** [comment]
The autoexecconfig include uses the transitional syntax, so you need at least sourcemod 1.7 to compile. I'd recommend using the latest stable release of SourceMod's spcomp though.

You could also get [an older version](https://github.com/Impact123/AutoExecConfig/tree/552e74fd3ef6cb2f891c39cc05bbeb396d7dfc27) of the autoexecconfig include before it was migrated to the transitional syntax.

**Comment by AllLuckNoSkill** [comment]
I have them installed, the error only comes up for smrpg. I am able to do everything else but that

**Comment by peace-maker** [comment]
What do you have installed exactly?

**Comment by AllLuckNoSkill** [comment]
everything installs but smrpg.smx

**Comment by peace-maker** [comment]
Have you tried using the older version of the autoexecconfig.inc I linked above? This is more of a problem with that third party include than this project itself, so you might get some luck posting in that thread.
