### ISSUE TITLE
Cannot buy upgrades

### ISSUE THREAD

**Issue by alpham8** [peace-maker/smrpg#23]
Hi, on my server I was not able to buy upgrades, because the menu point in rpgmenu is not available. Do I need credits to see it or went something else wrong?
The following plugins are loaded:
* 08 "SM:RPG > Credit Gifting" (1.0) by Peace-Maker
* 09 "SM:RPG > Chat Experience Stats" (1.0) by Jannik "Peace-Maker" Hartung
* 11 "SM:RPG > Counter-Strike Experience Module" (1.0) by Jannik "Peace-Maker" Hartung, SeLfkiLL
* 18 "SM:RPG > Command List" (1.0) by Jannik "Peace-Maker" Hartung
* 28 "SM:RPG > Effect Hub" (1.0) by Peace-Maker
* 31 "SM:RPG" (1.0) by Jannik "Peace-Maker" Hartung, SeLfkiLL

PS: This is not an April joke, this is a real problem. Pleas help me!

Cheers, alpham8

**Comment by peace-maker** [comment]
You have to compile and load every upgrade you want in the scripting/upgrades folder. They all are seperate plugins.

**Comment by alpham8** [comment]
Ok, thanks for your reply. If it is so, please write it also into the readme. It was not mentioned there.

**Comment by coty9090** [comment]
It does say it in the Installation... "Compile all the upgrades you want to use". The readme just explains support for css/csgo, not installation.
