### ISSUE TITLE
Not receiving XP

### ISSUE THREAD

**Issue by Rinzler135** [peace-maker/smrpg#231]
Hi,

I was editing the config file of SMRPG, and after reloading the server, neither me nor my friends received XP for kills, bomb plants, etc. I deleted the config file and replaced it with a backup copy, but it doesn't seem to have helped. I'm fairly sure it was the only thing that was changed.

I have checked, and I haven't accidentally toggled XP anywhere.

**Comment by peace-maker** [comment]
Any errors in the logs? Have you verified the convars have the values you expect by typing them without a value in the server console? Do you have the smrpg_cstrike plugin loaded?

**Comment by Rinzler135** [comment]
There doesn't appear to be any errors in the console or logs; I'm not sure which convars to verify, sorry; "sm plugins" reports `SM:RPG > Counter-Strike Experience Module" (1.0) by Jannik "Peace-Maker" Hartung, SeLfkiLL`

**Comment by peace-maker** [comment]
All the [convars listed](https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg_cstrike.sp#L76) in the plugin.smrpg_cstrike.cfg file and a [few of the convars](https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg.sp#L164-L188) in the core plugin.smrpg.cfg.

How are you testing? There are settings like `smrpg_need_enemies`, `smrpg_enemies_not_afk` and `smrpg_player_kill_bot` that might prevent you from earning XP when testing alone or only with bots.
