### ISSUE TITLE
Smrpg Resup

### ISSUE THREAD

**Issue by piotrekkrol7** [peace-maker/smrpg#234]
i have yet problem with this :) update yeahh
 L 11/29/2016 - 12:08:06: [SM] Blaming: smrpg_upgrade_resup.smx
L 11/29/2016 - 12:08:06: [SM] Call stack trace:
L 11/29/2016 - 12:08:06: [SM] [0] SetFailState
L 11/29/2016 - 12:08:06: [SM] [1] Line 48, smrpg_upgrade_resup.sp::OnPluginStart
L 11/29/2016 - 12:08:06: [SM] Unable to load plugin "smrpg_upgrade_resup.smx": Error detected in plugin startup (see error logs)

**Comment by peace-maker** [comment]
Have you tried grabbing the new gamedata?
