### ISSUE TITLE
sm rpg errro

### ISSUE THREAD

**Issue by piotrekkrol7** [peace-maker/smrpg#237]
Hi i update rpg and i have this `L 12/27/2016 - 11:21:39: [SM] Blaming: smrpg.smx
L 12/27/2016 - 11:21:39: [SM] Call stack trace:
L 12/27/2016 - 11:21:39: [SM]   [0] Format
L 12/27/2016 - 11:21:39: [SM]   [1] Line 804, smrpg.sp::CommandList_DefaultTranslations
L 12/27/2016 - 11:21:39: [SM]   [3] Call_Finish
L 12/27/2016 - 11:21:39: [SM]   [4] Line 426, smrpg_commandlist.sp::GetCommandTranslation
L 12/27/2016 - 11:21:39: [SM]   [5] Line 360, smrpg_commandlist.sp::Timer_ShowCommandAdvert
L 12/27/2016 - 11:21:39: [SM] Exception reported: Translation string formatted incorrectly - missing at least 1 parameters
L 12/27/2016 - 11:21:39: [SM] Blaming: smrpg.smx
L 12/27/2016 - 11:21:39: [SM] Call stack trace:
L 12/27/2016 - 11:21:39: [SM]   [0] Format
L 12/27/2016 - 11:21:39: [SM]   [1] Line 804, smrpg.sp::CommandList_DefaultTranslations
L 12/27/2016 - 11:21:39: [SM]   [3] Call_Finish
L 12/27/2016 - 11:21:39: [SM]   [4] Line 426, smrpg_commandlist.sp::GetCommandTranslation
L 12/27/2016 - 11:21:39: [SM]   [5] Line 360, smrpg_commandlist.sp::Timer_ShowCommandAdvert
L 12/27/2016 - 11:27:47: Error log file session closed.

i upload all with translations `

**Comment by peace-maker** [comment]
Thank you for reporting, that's a regression from the last update. It's fixed now.
