### ISSUE TITLE
Chat Tags module

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#238]
Do not use the color of the chat module
This is what is displayed: {Olive} [LVL50]
That's what it is established:
https://forums.alliedmods.net/showpost.php?p=2446728&postcount=336
https://github.com/KissLick/ColorVariables

**Comment by peace-maker** [comment]
Which game? Try writing the color in lower case `{olive}`.

**Comment by goodtime753** [comment]
CS:GO.  Recorded in lowercase :(


```
[SM] Blaming: smrpg/smrpg_effects.smx
[SM] Call stack trace:
[SM]   [0] CreateNative
[SM]   [1] Line 22, smrpg_effects/freeze.sp::RegisterFreezeNatives
[SM]   [2] Line 33, smrpg_effects.sp::AskPluginLoad2
[SM] Failed to load plugin "smrpg/smrpg_effects.smx": unexpected error 23 in AskPluginLoad callback.
[SM] Exception reported: Fatal error creating dynamic native!
[SM] Blaming: smrpg_commandlist.smx
[SM] Call stack trace:
[SM]   [0] CreateNative
[SM]   [1] Line 54, smrpg_commandlist.sp::AskPluginLoad2
[SM] Failed to load plugin "smrpg_commandlist.smx": unexpected error 23 in AskPluginLoad callback.
[SM] Exception reported: Fatal error creating dynamic native!
[SM] Blaming: smrpg.smx
[SM] Call stack trace:
[SM]   [0] CreateNative
[SM]   [1] Line 118, smrpg.sp::AskPluginLoad2
[SM] Failed to load plugin "smrpg.smx": unexpected error 23 in AskPluginLoad callback.
```

How to fix these errors?

**Comment by goodtime753** [comment]
and
```
[SM] Exception reported: Entity 113 is not valid
[SM] Blaming: smrpg/upgrades/smrpg_upgrade_impulse.smx
[SM] Call stack trace:
[SM]   [0] TeleportEntity
[SM]   [1] Line 241, smrpg_upgrade_impulse.sp::Hook_OnTakeDamagePost
```

**Comment by peace-maker** [comment]
CS:GO only supports a limited set of colors. Check out the color chart image in the ColorVariables README. Maybe {lime} would work for you?

Any other errors before the CreateNative ones in your first new comment?

I'll check the denial one out. Please create separate issues here next time, to keep track of different issues!

**Comment by peace-maker** [comment]
Fixed the impulse error in your last comment. If you get the native creation errors again, please open a new issue with the **full** error log from the beginning!
