### ISSUE TITLE
an experience

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#239]
Put a bomb, issued twice experience
Killing a player is given three times the experience
It shows like this: "You've got the experience for the murder of 123"
"You've got the experience for the murder of 123"
"You've got the experience for the murder of 123"
Accordingly, for one murder you get triple experience

What to do?

**Comment by goodtime753** [comment]
![2017-01-01_17-23-37](https://cloud.githubusercontent.com/assets/18263102/21581559/2818773e-d047-11e6-8cc0-cdbf7836f043.png)

**Comment by peace-maker** [comment]
Are you actually receiving the experience multiple times or is it just printed more than once? Check with the `rpgexp` chat command again.

**Comment by goodtime753** [comment]
![2017-01-02_16-51-30](https://cloud.githubusercontent.com/assets/18263102/21590909/a1b3838a-d110-11e6-878d-9ced6e14d030.png)
Write 4 times - issued 2 times
It depends...

**Comment by goodtime753** [comment]
My jamb. To use the old version in the same directory, and a new one in another. The old version of forgot to remove ...
