### ISSUE TITLE
cannot compile upgrades

### ISSUE THREAD

**Issue by alpham8** [peace-maker/smrpg#24]
I tried to compile an upgrade, but every upgrade sp file returns the following compiling error: ./compile.sh: line 7: 20138 Segmentation fault      ./spcomp $i -ocompiled/$smxfile

My server is running the last snapshot of sourcemod 1.6.3 under Linux.
When I try to compile it under another Linux machine, it gives me an memorry allocation error. On windows it compiles without any error, but the compiled folder is empty.

**Comment by coty9090** [comment]
use windows to compile. that's what i did.

**Comment by alpham8** [comment]
But as I said, it compiles without errors but no file is been created by the compiler...

**Comment by coty9090** [comment]
sounds like a permission problem not creating the files. (On a side note: i've previously had problems with windows not showing updated folders (also any new files in those folders didn't show and refreshing the desktop didn't help. I had to always log on/off my pc to see it updated.) Doubt it's that, but other than those i can't think of anything. If you can't get it to work, i can upload the  compiled files to dropbox or something.

**Comment by alpham8** [comment]
Thanks, it works now. The compilation output was taken to the wrong folder. My fault^^
