### ISSUE TITLE
hp problem

### ISSUE THREAD

**Issue by piotrekkrol7** [peace-maker/smrpg#240]
Hi i have video when i kill another player i lost hp any ideas? 
https://youtu.be/W9jQN9IWTBY
https://youtu.be/loPJ1WoR8Hg
https://youtu.be/_lg14iW1jXc

**Comment by peace-maker** [comment]
Is that on your own server? There might be some custom mirror damage upgrade on there? Does it happen on every kill? Which smrpg version do you use?

**Comment by piotrekkrol7** [comment]
Yes is is in my server. i don't have mirror damage and not all people have a problem. i have new 481 and in 480 have the same problem ;/

**Comment by piotrekkrol7** [comment]
@peace-maker  and ? i have problem all the time. and with denial.

**Comment by peace-maker** [comment]
Can you paste your `sm plugins list` from the server console? I don't know how this could happen with smrpg, so it might be some other plugin.
