### ISSUE TITLE
I'm a complete noob in this Please Help! <3

### ISSUE THREAD

**Issue by Stefanoss** [peace-maker/smrpg#241]
So I remember this RPG mod from CSS I really loved it and now I dont see any server with it and that's why I really want to make my own server with it and woahhh it's complicated! 
Could someone guide me through this or help me or something! Haha

Folders I have : Configs - Gamedata - Helper_scripts - scripting - translations
Files : .gitignore - .travis.yml - compile.sh

Any help or short guide really appreciated! <3
Thanks alot!

**Comment by peace-maker** [comment]
There are a few servers running this RPG plugin, you could try looking on some [tracking sites](http://www.gametracker.com/search/?search_by=server_variable&search_by2=smrpg_version&query=&loc=_all&sort=&order=) for servers. There are some for csgo too, but they don't show up there by default.

If you want to setup your own, read the install instructions in the README.
