### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#243]
SM 1.8 last stable
scripting\smrpg.sp(406) : error 100: function prototypes do not match
scripting\smrpg_antisuicide.sp(59) : error 100: function prototypes do not match

**Comment by peace-maker** [comment]
Update your sourcemod includes. You seem to have missed to replace the include files that come with sourcemod when updating the spcomp. Especially the sdkhooks.inc.
