### ISSUE TITLE
Everything works, except for the effects. 

### ISSUE THREAD

**Issue by Riguy2002** [peace-maker/smrpg#247]
I'm new to this sort of stuff, and this is one of the first things I've done with CS:GO. I made a server to play with friends, and everything works, except when you buy an effect, nothing happens. It says you own it, says it's active, but it just doesn't do anything.

**Comment by peace-maker** [comment]
Which effect/upgrade isn't working for you?

**Comment by Riguy2002** [comment]
None of them.

**Comment by peace-maker** [comment]
Works for everyone else so please provide more information about your config.
Please paste the output of `sm plugins list` and `sm exits list` from the server console.
How are you testing the upgrades?

**Comment by Riguy2002** [comment]
I'm starting a private server, through csgosl, but I think it's actually my sourcemod installation.
