### ISSUE TITLE
[Request] Add an admin option for no refunds

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#248]
I would like there to be an option to reset a players upgrade with no refund. I was testing a skill (the AntiFlash, which works great!) and gave myself max level at no cost and realized that i couldn't undo the upgrade without earning skill points.

**Comment by peace-maker** [comment]
You could use the admin command `smrpg_setupgradelvl @me antiflash 0` or use `smrpg_takeupgrade @me antiflash` a few times. See [the wiki here](https://github.com/peace-maker/smrpg/wiki/Admin-commands#change-upgrade-levels-without-changing-credits).

The admin menu is pretty limited in what the commands allow. That might need some rework to support all combinations.
> Usage: smrpg_setupgradelvl <player name | #userid | #steamid> <upgrade shortname> <level|max>

**Comment by coty9090** [comment]
thanks... completely forgot about a lot of those commands!

**Comment by peace-maker** [comment]
The admin menu allows to do everything (and even more) that the commands can do now.
