### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#249]
L 02/19/2017 - 21:24:56: [SM] Exception reported: Language phrase "new_lvl1" not found
L 02/19/2017 - 21:24:56: [SM] Blaming: smrpg/smrpg.smx
L 02/19/2017 - 21:24:56: [SM] Call stack trace:
L 02/19/2017 - 21:24:56: [SM]   [0] VFormat
L 02/19/2017 - 21:24:56: [SM]   [1] Line 377, C:\Users\vBDSK\Desktop\scripting\include\halflife.inc::PrintToChatAll
L 02/19/2017 - 21:24:56: [SM]   [2] Line 448, smrpg/smrpg_adminmenu.sp::Menu_HandlePlayerChangeLevel

**Comment by peace-maker** [comment]
Whops. Looks like there aren't many users of that feature ;)
Thanks!
