### ISSUE TITLE
Grenade Resupply

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#25]
I know it's experimental, but it doesn't even do anything at any level.

**Comment by peace-maker** [comment]
It's supposed to give you a grenade back after you used one.

**Comment by coty9090** [comment]
It doesn't give any grenades back. I've had made regen maxed (level 5?) for a few days now and not once has it given me a grenade after I've thrown one. So are the levels for how much faster it gives you a grenade, or the increased chance to get a grenade?

**Comment by coty9090** [comment]
just realized i didn't have the nade regen delay cfg...  -.-  it works good now lol
