### ISSUE TITLE
[help pls] no where to go.

### ISSUE THREAD

**Issue by pandaramicz** [peace-maker/smrpg#250]
So I have loaded all the files and everything but with all this compile stuff I am completely lost. I have read all the readme files and everything but I am stuck. I would appreciate some help. thanks!

**Comment by pandaramicz** [comment]
sm plugins list
[SM] Listing 19 plugins:
01 "Client Preferences" (1.8.0.5964) by AlliedModders LLC
02 "Nade Tails" (2.0) by InternetBully
03 "Basic Comm Control" (1.8.0.5964) by AlliedModders LLC
04 "Nextmap" (1.8.0.5964) by AlliedModders LLC
05 "Admin Help" (1.8.0.5964) by AlliedModders LLC
06 "Player Commands" (1.8.0.5964) by AlliedModders LLC
07 "Reserved Slots" (1.8.0.5964) by AlliedModders LLC
08 "Admin Menu" (1.8.0.5964) by AlliedModders LLC
09 "Basic Commands" (1.8.0.5964) by AlliedModders LLC
10 "Fun Commands" (1.8.0.5964) by AlliedModders LLC
11 "Fun Votes" (1.8.0.5964) by AlliedModders LLC
12 "Basic Votes" (1.8.0.5964) by AlliedModders LLC
13 "Basic Ban Commands" (1.8.0.5964) by AlliedModders LLC
14 "Anti-Flood" (1.8.0.5964) by AlliedModders LLC
15 "Basic Info Triggers" (1.8.0.5964) by AlliedModders LLC
16 "Admin File Reader" (1.8.0.5964) by AlliedModders LLC
17 "Sound Commands" (1.8.0.5964) by AlliedModders LLC
18 "Basic Chat" (1.8.0.5964) by AlliedModders LLC
19 "[CSS/CS:GO] AbNeR Bunny Hoping" (1.5) by AbNeR_CSS


The plugin does not show up either

**Comment by peace-maker** [comment]
There is a link right at the top of the compile instructions to download a precomputed package!
http://build.wcfan.de/smrpg/1.8/

**Comment by pandaramicz** [comment]
thanks
