### ISSUE TITLE
bouncybullets

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#252]
I bet smrpg_bouncybullets_force 100
Result: no repulsion, just stops on the spot
What's the matter?

**Comment by peace-maker** [comment]
In CS:GO? Does it work if you shoot someone while he jumps?

**Comment by goodtime753** [comment]
Yes

**Comment by peace-maker** [comment]
So does it work in the air or not?

**Comment by goodtime753** [comment]
Simply stops, but does not repel

**Comment by baferpro** [comment]
+1

**Comment by peace-maker** [comment]
I guess you'll need the [Movement Unlocker](https://forums.alliedmods.net/showthread.php?t=255298) for CS:GO to fix that. It's the same issue that haunted "knockback" in zombiemod. I'll add a notice to the readme.
