### ISSUE TITLE
Frost Pistol/Ice Stab issue

### ISSUE THREAD

**Issue by Unkn0wn96** [peace-maker/smrpg#253]
The movement speed reduction created by either frost pistol and ice stab stacks and is permanent until the target no longer can move, this effect only dissapears when the target respawns. Primary weapons such as non-pistol guns seem to also be slowing down the target with a permanent effect. This also works for team damage, when a team mate shoots another team mate and he gets slowed down for a permanent duration.

Game : CSGO
[Frost Pistol.cfg] - https://pastebin.com/Zkp10DME 
[Ice Stab.cfg] - https://pastebin.com/nfRZsqN2

I even tried to remove all frost related files from the server directory and the movment speed reduction is still active, including disableing both upgrades both ingame and in the cfg files as provided.

**Comment by peace-maker** [comment]
Can you paste the output of `sm plugins list` from your server console?

**Comment by Unkn0wn96** [comment]
[sm plugins list] - https://pastebin.com/q3ebeLTf

**Comment by Unkn0wn96** [comment]
If it would be of any help and if you have the game, you could add me on steam to get a live preview of the issue. 

[Steam] - https://steamcommunity.com/id/Unkn0wing/

**Comment by peace-maker** [comment]
Is it still happening when you disable the smrpg_effects plugin? It sounds like it's some other external issue not directly related to smrpg.
I don't have a computer which is fast enough to run csgo atm..

**Comment by Unkn0wn96** [comment]
After further testing with the smrpg_effects plugin disabled [removed from the server directory], the problem is still unsolved, for each bullet you take of any gun or knife you still get a slow effect which stacks until you no longer can move...

If it would be an external issue, I can't seem to figure out what is causing it to happen. Hopefully you have some insight.

**Comment by peace-maker** [comment]
The smrpg_effects plugin is the only one messing with the lagged movement value, so I'm assuming it's some other plugin on your server causing it. Did you try to narrow it down to a certain plugin?
First start with all plugins removed and then load them one after the other until it happens again.

**Comment by Unkn0wn96** [comment]
I solved the issue, it was no plugin who caused the issue, however it was a simple cfg error on my end. So your rpg system stands free! 

The problem was sv_staminarecoveryrate 0 which is ran for bunnyhopping. However I never considered that it is required to recover from other things such as damage. Thanks how ever for assisting me trough it, even thought!
