### ISSUE TITLE
[Enhancement] Allow sell upgrade even if upgrade is disabled

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#255]
So I am running 2 parallel servers both use the same db, and some upgrades are disabled on one server,  but those who have them in other server when joining 2nd can't sell them they have to jump from server to server, which is annoying to the players just to sell upgrades.

**Comment by peace-maker** [comment]
You can set the new `smrpg_allow_sell_disabled_upgrade` convar to 1 for that!
