### ISSUE TITLE
Ability "Speed"

### ISSUE THREAD

**Issue by goodtime753** [peace-maker/smrpg#256]
Why "Speed" does not affect gravity?
When the "pulse" is triggered, gravity changes

**Comment by peace-maker** [comment]
Because they are using different methods to increase the speed.

**Comment by goodtime753** [comment]
Can I change the method?

**Comment by peace-maker** [comment]
There's a new convar to change the Speed+ upgrade to behave like the old method used in THC:RPG and prior: `smrpg_speed_method`.
