### ISSUE TITLE
Speed ability doesn't work since the csgo update 23.05.2017

### ISSUE THREAD

**Issue by Calvinoux** [peace-maker/smrpg#257]
Hi, the speed ability doesn't work anymore since the csgo update ( 23.05.2017 ), 

I want to know does it still working for you?

**Comment by Calvinoux** [comment]
Edit :CS:GO server

**Comment by peace-maker** [comment]
Updated the gamedata for the speed upgrade. Thanks for reporting!

**Comment by Calvinoux** [comment]
No sir, thank to you for make us peace ! :D
