### ISSUE TITLE
Sell Menu

### ISSUE THREAD

**Issue by Unknown96** [peace-maker/smrpg#258]
Greetings again, I just noticed that the sell upgrades menu is all messed up. After I noticed the issue I tried to change rpgmenu_sorting > "RPGSellMenu" but that didn't change anything.

I'm also wondering if there's a way to earn more experience if you either is in a specific steam group or have a rank.

http://imgur.com/a/7fqS5

sm plugins list [https://pastebin.com/ddtRQGZS]
Game: Csgo

**Comment by peace-maker** [comment]
The sell menu looks here :(
What happens when you select those empty options?

**Comment by peace-maker** [comment]
I can't reproduce this and it looks like it's some problem with the topmenus extension entering a bad state. Maybe due to plugins reloading or something?
