### ISSUE TITLE
Mysql Query hmmm....

### ISSUE THREAD

**Issue by deven10100** [peace-maker/smrpg#259]
So some csgo updates happend this symbol in steam names 🔥  was crashing my server now its not 

So now your name in-game gets changed  to box symbols [][] if you use that fire character in your steam name

Now those box symbols just cannot query and update to my database so it does not save my levels with that symbol in my name and any other players who use it aswell.,

please try this and also when it says you have changed your name in chat try to copy the box symbols and paste it into your steamname again, they magically appear to be that fire symbol again,

Here is the error for that symbol

[smrpg.smx] Error executing query 0 of 2 queries: Incorrect string value: '\xF0\x9F\x94\xA5' for column 'name' at row 1

I changed my database collation to utf8mb4_unicode_ci is the most updated and should support a symbol like that right? Hmm i still get the query error after i also tried utf8_general_ci, and latin1_swedish_ci, am i missing one :P

 i am on the latest version of mysql.

**Comment by peace-maker** [comment]
Did you fix that issue?

**Comment by deven10100** [comment]
It was either me changing my MYSQL server default collation to utf8mb4_unicode_ci

and entering these into my "my.cnf" file 

character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

//
Or an update to csgo fixed it.

Cannot remember sorry. 

I do remember checking after this and it stopped crashing my server, but the symbol still would not save to my database.
