### ISSUE TITLE
[Feature Request] - Disabling Stats Panel

### ISSUE THREAD

**Issue by killertudse** [peace-maker/smrpg#264]
Greetings.

I am unsure if I am just completely blind - But i cannot find a config that allows me to disable the RPG stats panel in the middle of the screen? Only inside of the settings for each individual player - However i would like to be able to disable it server-side

**Comment by Nobody-x** [comment]
Hi,

Simply remove smrpg_keyhint_info.smx from the plugins will disable this feature.

**Comment by peace-maker** [comment]
Do you just want to set the default visibility, but still allow players to activate it if they want to? Otherwise @Nobody-x is right.

**Comment by peace-maker** [comment]
Well there is a new cvar `smrpg_hide_infopanel_default` to hide the panel for new players by default now either way. Choose what you like.
