### ISSUE TITLE
Suggestion for Turbo Mode

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#266]
The Plugin SM: RPG, contains a Turbo Mode option, which would be a setting that when it activates, it makes all players, gain experience X, X credits X times more than normal.

But by activating it, all players are reset to Level 1, and when I disable Turbo Mode, it again resets all players to Level 1, and restarts the map, and the stats that the Players were before I started Turbo Mode, back.

I would like to know if the plugin actually works like this, or is it a bug, and if it is a bug, how can I solve it?

Because I wish it worked like this:
When Turbe Mode is activated, players will keep all of their experience, levels and credits they currently have, and when Turbe Mode is finished, the experience it gained while Turbe Mode was activated would add to what it already has, without losing any given away.

Is it possible to do this?

Sorry for the lousy English :(

**Comment by peace-maker** [comment]
The intended behavior is indeed to just have a short "fun" round that doesn't affect the actual experience of the players as you described.

I can add an option to just increase the experience rate for a while without disabling data saving.

**Comment by coty9090** [comment]
That would be awesome! +1 to this.

**Comment by paulocrash** [comment]
Perfect, I'll be waiting for this update.

**Comment by peace-maker** [comment]
You can set the new `smrpg_turbomode_persist_changes` convar to 1 to have the players keep their stats during and after turbo mode now.

**Comment by paulocrash** [comment]
@peace-maker just a doubt with this new option.

Example, if the player is at level 5, then active Turbo Mode is it still at Level 5?

Levels that he picks up in Turbo Mode adds up to this 5 Level he already has at the end of Turbe mode?

Is this the way it works?

**Comment by peace-maker** [comment]
Yes, the player level isn't touched when turbo mode is (de)activated. So he will continue on from level 5 and keep what he earned after you disable turbo mode again.
