### ISSUE TITLE
smrpg skill config not generating?

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#267]
When running smrpg, the skill configs are not being created, the cfg\sourcemod\smrpg folder is empty.

**Comment by peace-maker** [comment]
Does the folder has the right permissions so the gameserver user can write to it? Works for me.

**Comment by VOLKRuS** [comment]
I have the same problem, files generating at ../csgo/ folder, without ".cfg". cfg/sourcemod/smrpg/ is empty.

**Comment by coty9090** [comment]
Alright, it still won't work even after setting chmod to 777 for the smrpg folder, usually that works if it is a permissions issue... something is up.

**Comment by CrazyGhostRider** [comment]
And I have the same problem. Configs are created in the folder "tf", without ".cfg". "cfg/sourcemod/smrpg/" is empty.

I use: Windows, sm1.8.0.6039 and mms1.10.7

**Comment by coty9090** [comment]
no recommendations?

**Comment by peace-maker** [comment]
The only thing I can think of is the autoexecconfig include got broken in one of the updates to it. I don't have time to investigate, but you can try to use an older version of that and compile yourself.

**Comment by CrazyGhostRider** [comment]
I conducted the analysis.
The latest working version of AutoExecConfig 0.1.2
https://github.com/Impact123/AutoExecConfig/tree/514895a1da0c9f1a41afa39cfe19f4a388f66c1f

Any newer version (since adding "Return error if folder given to AutoExecConfig_FormatFileName has sla ...") does not work

**Comment by peace-maker** [comment]
Thanks to @Impact123's fast response this is fixed now. The latest build should have used the new autoexecconfig include and generate the files in the right folder again.
