### ISSUE TITLE
Issue after newest csgo update + sm1.7 support?

### ISSUE THREAD

**Issue by Raritylicious** [peace-maker/smrpg#27]
Some upgrade modules stopped working since today's csgo update.

So far, I have noticed speed module isn't working.

Secondly, do you have any plan for supporting sm1.7?

PS: Would appreciate if you won't just close this thread down instantly as before.
Btw, my sourcemod version is 1.7.2

**Comment by Raritylicious** [comment]
And, yea.
I was using smrpg with sm1.7+ and it was working just fine except the sql connection issues + couldn't compile.

**Comment by erikxcore** [comment]
Seeing the same issues I believe, after yesterday's update with the Falchion and Operation Bloodhound with SM 1.7

L 05/27/2015 - 11:52:55: Info (map "cs_office") (file "errors_20150527.log")
L 05/27/2015 - 11:52:55: [SM] Native "GetClientCookie" reported: Invalid Cookie handle 0 (error 4)
L 05/27/2015 - 11:52:55: [SM] Displaying call stack trace for plugin "disabled/smrpg_commandlist.smx":
L 05/27/2015 - 11:52:55: [SM]   [0]  Line 124, smrpg_commandlist.sp::OnClientCookiesCached()
L 05/27/2015 - 11:58:11: [SM] Native "GetConVarFloat" reported: Invalid convar handle 0 (error 4)
L 05/27/2015 - 11:58:11: [SM] Displaying call stack trace for plugin "disabled/smrpg_cstrike.smx":
L 05/27/2015 - 11:58:11: [SM]   [0]  Line 368, smrpg_cstrike.sp::Event_OnRoundEnd()
L 05/27/2015 - 11:58:15: [SM] Native "GetClientCookie" reported: Invalid Cookie handle 0 (error 4)
L 05/27/2015 - 11:58:15: [SM] Displaying call stack trace for plugin "disabled/smrpg_commandlist.smx":
L 05/27/2015 - 11:58:15: [SM]   [0]  Line 124, smrpg_commandlist.sp::OnClientCookiesCached()
L 05/27/2015 - 12:00:03: [SM] Native "GetConVarFloat" reported: Invalid convar handle 0 (error 4)
L 05/27/2015 - 12:00:03: [SM] Displaying call stack trace for plugin "disabled/smrpg_cstrike.smx":
L 05/27/2015 - 12:00:03: [SM]   [0]  Line 368, smrpg_cstrike.sp::Event_OnRoundEnd()

Haven't noticed any particular modules not working, but I don't play on this server all that often. Haven't heard any complaints directly but messages in the log are alarming after an update, haha.

Particularly seeing a lot of errors stemming from smrpg_cstrike.smx and smrpg_commandlist.smx (cookie error might be something wrong with ClientPrefs....unsure about cstrike).

Sorry if this is totally unrelated.

**Comment by peace-maker** [comment]
I've updated the gamedata for the speed upgrade.
What's the problem with sm1.7? I only see some tag mismatch warnings due to new return types of some functions, but they won't break anything.

Those other errors look like they're coming from lateloading the plugins in the wrong order? The smrpg_cstrike module can't find convars which get registered by the core smrpg plugin.
smrpg_commandlist fails to register a cookie in clientprefs. Might have overwritten your databases.cfg while upgrading sourcemod?

**Comment by Raritylicious** [comment]
Thanks for your reply.

Will there be any chance that you might update smrpg so it would be compileable with sm1.7 compiler ?

**Comment by peace-maker** [comment]
It's working fine with SM1.7. You can ignore the tag mismatch warnings.
