### ISSUE TITLE
[Upgrade Request] Include Automatic Update

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#272]
It would be possible to include in the plugin the Update include, so whenever you launch an update in Git the plugin automatically updates on the servers that are using it.

**Comment by peace-maker** [comment]
I don't know how easy it is to create patches for updater automatically on new commits. And I don't know if we'd really want that. I don't have actual releases, so everything is just "1.0-xxx". Sometimes upgrading requires changes to the configs or other manual work. We'd probably want a seperate "release"/"stable" branch that gets updated from time to time where the updater is bound to.

The plugin isn't updated that often lately usually, so having people update manually like once a month doesn't seem too bad.

**Comment by paulocrash** [comment]
I understand, thank you anyway!
