### ISSUE TITLE
[Suggestion]RPGBan

### ISSUE THREAD

**Issue by baferpro** [peace-maker/smrpg#275]
Add admin menu rpg ban
-Block take exp
-Block all upgrades
The ban is given for a time
Example:
Admin Name1 baned Name2 on 2 hours, reason: non-observance of rules

**Comment by peace-maker** [comment]
Funny idea. Other players would still get experience for killing banned players though, right?

Why do you just want to disable the rpg features for a player and not just ban him straight away?

**Comment by baferpro** [comment]
1)right
2)Some rules are not worth the ban on the server, but simply rpgban
So there will be more opportunities for new ideas with bans and players will be more interesting.

**Comment by paulocrash** [comment]
It would really be a great suggestion, as he said, RPGBAN.

It would ban in a player for a certain time, during the banishment it could not buy Upgrades, it would not gain Experiences and nor Credits, let's say that would only be with the ones that it has before taking the banishment.

Other players could kill it normally, and of course, the banned player could also kill other players.

Would this update be possible?

**Comment by baferpro** [comment]
Yes, for example sm_rpgban {NAME} {TIME} {REASON}
You can also add this to the admin menu.

**Comment by paulocrash** [comment]
Anything new about this function, would it have some date to add it?

**Comment by peace-maker** [comment]
I think it's done now in #289. I'll let it sit for a day to see if something comes to mind and merge it afterwards.

**Comment by peace-maker** [comment]
There you go.
