### ISSUE TITLE
[Report] Bug: Turbo Mode and Upgrade Clipsize

### ISSUE THREAD

**Issue by biielzk** [peace-maker/smrpg#277]
**Hello**

- When there was a update of turbomode, you added configuration of not reset the player, a bug came up. When a player enters and the turbomode is already activated, it is automatically reset to level 1.

- And when you refresh the size of the clip, when you take a gun, which is not replenished with the player, a bullet of 30 bullets of ammunition wins 10 and this varies.

**Comment by paulocrash** [comment]
Just to better explain the ClipSize BUG, ​​it happens like this.

And in the clipsize when you take a gun that is generated on the ground, the beginning of the round does not come with all bullets, and when you click to recharge it the comb does not come complete.

Now the guns you grab by pressing the map buttons or even straight into them to catch comes normal.

**Comment by peace-maker** [comment]
The first issue with turbo mode is fixed now.

So the clipsize of weapons spawned by the map or by other plugins isn't increased when they're picked up by players who bought the upgrade?

**Comment by paulocrash** [comment]
The BUG of Turbo Mode has been fixed, thank you.

Now only the Clipsize that I mentioned is missing.

**Comment by Z-RAY-Z** [comment]
I was hear about clip-size bug form players in my server and i come, saw and reproduse this.
When you pickup a gun from a map - you got clip bug.
When you buy a gun - all works fine.
I was disable ClipSize Upgrade and am hope you'll fix it soon.

**Comment by peace-maker** [comment]
The clip of weapons spawned on the floor should be increased now properly.
