### ISSUE TITLE
skills reset and errors

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#28]
It was fine until map change, then all my rpg skills got reset back to 1 but my rpg level stayed the same. After i did a map change again it loaded my player data correctly.

This error is the only one that stays after  it correctly loads the player data.

[SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/02/2015 - 19:38:07: [SM] Native "Format" reported: Language phrase "grenaderesup" not found
L 06/02/2015 - 19:38:07: [SM] Displaying call stack trace for plugin "smrpg_upgrade_grenaderesup_cstrike.smx":
L 06/02/2015 - 19:38:07: [SM]   [0]  Line 189, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_upgrade_grenaderesup_cstrike.sp::SMRPG_TranslateUpgrade()
L 06/02/2015 - 19:38:07: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/02/2015 - 19:38:07: [SM] Native "Format" reported: Language phrase "grenaderesup" not found

These are the ones i got when it incorrectly loaded the player data.

L 06/02/2015 - 15:23:00: [SM] Native "GetArrayArray" reported: Invalid Handle 0 (error: 4)
L 06/02/2015 - 15:23:00: [SM] Displaying call stack trace for plugin "smrpg.smx":
L 06/02/2015 - 15:23:00: [SM]   [0]  Line 358, smrpg/smrpg_players.sp::GetPlayerUpgradeInfoByIndex()
L 06/02/2015 - 15:23:00: [SM]   [1]  Line 411, smrpg/smrpg_players.sp::IsClientUpgradeEnabled()
L 06/02/2015 - 15:23:00: [SM]   [2]  Line 936, smrpg/smrpg_players.sp::Native_GetClientUpgradeLevel()
L 06/02/2015 - 15:23:00: [SM] Native "SMRPG_GetClientUpgradeLevel" reported: Error encountered while processing a dynamic native

L 06/02/2015 - 15:23:00: [SM] Displaying call stack trace for plugin "smrpg_upgrade_poisonsmoke.cstrike.smx":
L 06/02/2015 - 15:23:00: [SM]   [0]  Line 443, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_upgrade_poisonsmoke.cstrike.sp::SMRPG_CanRunEffectOnClient()
L 06/02/2015 - 15:23:00: [SM]   [1]  Line 212, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_upgrade_poisonsmoke.cstrike.sp::Hook_OnSpawnProjectile()
L 06/02/2015 - 18:42:45: [SM] Native "SMRPG_ChangeClientLaggedMovement" reported: Invalid effect time 0.000000.

L 06/02/2015 - 18:42:45: [SM] Displaying call stack trace for plugin "smrpg_upgrade_fpistol.smx":
L 06/02/2015 - 18:42:45: [SM]   [0]  Line 202, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_upgrade_fpistol.sp::Hook_OnTakeDamagePost()

L 06/02/2015 - 19:19:35: [smrpg.smx] Unable to load item data (database disk image is malformed)
L 06/02/2015 - 19:20:06: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/02/2015 - 19:20:06: [SM] Native "Format" reported: Language phrase "grenaderesup" not found

L 06/02/2015 - 19:20:06: [SM] Displaying call stack trace for plugin "smrpg_upgrade_grenaderesup_cstrike.smx":
L 06/02/2015 - 19:20:06: [SM]   [0]  Line 189, C:\Users\Coty\Desktop\New folder\New folder\addons\sourcemod\scripting\smrpg_upgrade_grenaderesup_cstrike.sp::SMRPG_TranslateUpgrade()
L 06/02/2015 - 19:20:06: [SM] Plugin encountered error 4: Invalid parameter or parameter type
L 06/02/2015 - 19:20:06: [SM] Native "Format" reported: Language phrase "grenaderesup" not found

**Comment by peace-maker** [comment]
> [smrpg.smx] Unable to load item data (database disk image is malformed)

That's the important error you're having problems with. Are you using sqlite?

The other errors are harmless. 
>  [SM] Native "Format" reported: Language phrase "grenaderesup" not found

You seem to use the "beta" grenade resupply plugin but missed the changes to the translation file translations/smrpg_stock_upgrades.phrases.txt.

> [SM] Native "GetArrayArray" reported: Invalid Handle 0 (error: 4)

That's an actual bug if you try to get the upgrade info of an unconnected client. I don't know why the poisonsmoke upgrade is trying to fetch info about invalid clients though..

> [SM] Native "SMRPG_ChangeClientLaggedMovement" reported: Invalid effect time 0.000000.

You've set smrpg_fpistol_inc of the frost pistol upgrade to 0.0? That doesn't make sense. If you don't want any slowdown, just disable the upgrade. I'll patch it up to not allow that setting.

**Comment by coty9090** [comment]
i am using sqlite. I have the smrpg_fpistol_inc set to 0.1 (default)... But i do have max level antidote set to 1.0

**Comment by peace-maker** [comment]
I'd assume you already googled that "database disk image is malformed" sqlite error and restored your database? Looks like this can happen to sqlite, if the server crashes while a transaction is running. Nothing this plugin can fix.

asherkin pointed me towards the issue with that GetArrayArray handle error, but the fix is pending testing.
