### ISSUE TITLE
[Issue] Chat Tags not working

### ISSUE THREAD

**Issue by GryTrean** [peace-maker/smrpg#280]
Hello!

I have some issues installing the Chat Tags plugin. The core is working fine - XP is given, players can level up, there is a connection to the database and it's getting updated. The issue though is, that I can't manage to get tags (ie. prefixes) for the chat. I've tried to install the compiled version and to compile it myself, I have tried both with chat-processor and a version of simple-chat-processor I found. I've tried to find the issue looking at the sourcecode myself, but I can't manage to get it to work.

From what I've managed to check - the "OnChatMessage' action is never called. I added a PrintToChatAll at the beginning of that action and it's never sent to the server (the plugin is loaded for sure, I used the same technique in OnPluginStart and that message is sent).

How can I resolve this issue?

Thanks for your time,
Best regards,
Krystian

**Comment by peace-maker** [comment]
I'm not sure PrintToChat* is working in the OnChatMessage forward. Try adding a debug output using PrintToServer instead. Which game?

**Comment by GryTrean** [comment]
I will try it later on today, but I don't think that's the issue. I tried editing the format of the message  (where the lvl should be added), and the change wasn't visible on the server.

The game is CS:GO, newest stable build of sourcemod  (I believe it's 1.8).

**Comment by GryTrean** [comment]
I have no idea why (I have not changed anything, except for adding PrintToServer), but it is now working.
Thanks for your time I guess :D
