### ISSUE TITLE
[BUG] Database version incompatible

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#281]
Plugin started to present the following error in the console on the database used in it:
``L 05/14/2018 - 14:43:09: [smrpg.smx] Database version 103 is newer than supported by this plugin (102). There might be problems with incompatible database structures!``
As you can see it speaks that the version of the database used by the plugin is old, could it update, or how can I fix it myself?

**Comment by peace-maker** [comment]
You should upgrade to the latest smrpg again, so it uses the new database structure.

Looks like you once updated smrpg and reverted to an older version afterwards again.

**Comment by paulocrash** [comment]
Problem solved, I resubmitted the plugin to the server and apparently it was fixed.

**Comment by paulocrash** [comment]
I sent the plugin again, until that worked everything right, except that I rebooted the server and the message appeared again.

**Comment by peace-maker** [comment]
Are you using the [latest build](http://build.wcfan.de/smrpg/1.8/smrpg-rev518.tar.gz)?

**Comment by peace-maker** [comment]
I guess it's fine now.
