### ISSUE TITLE
Why max level don`t change?

### ISSUE THREAD

**Issue by baferpro** [peace-maker/smrpg#283]
in /cfg/sourcemod/smrpg/smrpg_upgrade_damage.cfg
`// Damage+ upgrade maximum level. This is the maximum level players can reach for this upgrade.
// When changed, all players who bought a higher level before are refunded with the full upgrade costs and set down to the new maxlevel.
// -
// Default: "5"
// Minimum: "1.000000"
smrpg_damage_maxlevel "60"`
In console 
`"smrpg_damage_maxlevel" = "10" ( def. "5" ) min. 1.000000                        - Damage+ upgrade maximum level. This is the maximum`
How can I correctly change the maximum level if  do not work just through the config?

And i use 
`sm_rcon smrpg_damage_maxlevel 60` in game. But also zero effect

**Comment by baferpro** [comment]
Actually so with all the upgrades.
The remaining cvars change.

**Comment by peace-maker** [comment]
Set `smrpg_ignore_level_barrier` to 1! Some upgrades aren't written to handle an unlimited amount of levels, so they restrict the max level convar. Ignore those valid limits at your own risk. Some upgrades don't really have a reason to still have that barrier, so you're probably fine.
