### ISSUE TITLE
[BUG] Upgrade clipsize + Shotgun

### ISSUE THREAD

**Issue by baferpro** [peace-maker/smrpg#288]
When start reload weapon then breaks down anim ( endless reload ) and ammunition are not replenished. Only if you shoot. Can be fixed?

**Comment by peace-maker** [comment]
This is a duplicate of #121. It's just tedious to reverse engineer the shotgun reloading code and I haven't got around to it yet. I'll bump it up.

**Comment by baferpro** [comment]
Okay, thx.
