### ISSUE TITLE
Denial upgrade doesn't respect inventory selection?

### ISSUE THREAD

**Issue by Raritylicious** [peace-maker/smrpg#29]
Denial module have some problems with CZ75 Pistol and M4A1-S

CZ75 would turn into P250 and M4A1-S would turn into M4A1

Some other weapons may have similar problems.

There is a bug where you can generate unlimited amount of grenades after respawning or something.
I couldn't figure out how exactly it happens yet tho.

**Comment by maxgraham** [comment]
yea I noticed it as well that it doesnt matter if i have an M4A1 or M4A4 (i think these are two different), anyway it always gives me the unsilenced version while i had the silenced

**Comment by peace-maker** [comment]
Seems like this is enough. Still bad to have to hardcode values :(
