### ISSUE TITLE
[DOUBT] I do not earn credits when I level up

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#294]
You would have a question with the option to earn credits when you level up.

I was in Level 12 and I went up to Level 13, but I did not get any credits. This would be normal, in the Low Levels it was normal.

Is it correct or is it a BUG?

**Useful Information:**
**SourceMod:**  1.9 - build 6248
**Metamod:** 1.10 - build 966
**SM:RPG:** smrpg-rev532.tar.gz - 2018-08-16 18:14
**MySQL Database:**  5.6.40 - MySQL Community Server (GPL)

###### Sorry for my bad English, if you do not understand let me know that I try to explain better.

**Comment by Z-RAY-Z** [comment]
Check you SM error logs - maybe SM:RPG just can't connect to DB.

**Comment by paulocrash** [comment]
@Z-RAY-Z check the log and you have these errors:
```
L 09/03/2018 - 13:51:58: [smrpg.smx] Error executing query -1 of 2 queries: Lost connection to MySQL server at 'reading initial communication packet', system error: 111
L 09/03/2018 - 13:52:07: [smrpg.smx] Error executing query -1 of 12 queries: Lost connection to MySQL server at 'reading initial communication packet', system error: 111
L 09/03/2018 - 14:07:08: [smrpg.smx] Error executing query -1 of 10 queries: Lost connection to MySQL server at 'reading initial communication packet', system error: 111
L 09/03/2018 - 14:09:38: [smrpg.smx] Error executing query -1 of 10 queries: Lost connection to MySQL server at 'reading initial communication packet', system error: 111
```
Here is the complete error log: [errors_20180903.log](https://github.com/peace-maker/smrpg/files/2346620/errors_20180903.log)

Is this an error in the case of a Host Host error?

I only have problem with the RPG, other database that I use in my servers I have no problem, they work normally.

**Comment by peace-maker** [comment]
```
L 09/03/2018 - 13:58:01: [sm_ctban.smx] Error in OnClientAuthorized query: Lost connection to MySQL server at 'reading initial communication packet', system error: 111
```

It isn't only smrpg failing. That error usually means that the MySQL client tried to connect to a server that wasn't a MySQL server. Is your MySQL server running on a different port than the default `3306`?

**Comment by paulocrash** [comment]
@peace-maker port default ``3306``.

Here are some screenshots of my database information:
![screenshot_1](https://user-images.githubusercontent.com/32937653/45004621-97cc4e80-afc4-11e8-8bdb-ad29518b50c2.png)
![screenshot_2](https://user-images.githubusercontent.com/32937653/45004622-9864e500-afc4-11e8-8129-b6c3201a7235.png)

...

**Comment by peace-maker** [comment]
This is a problem with your database host or network. I can't help you here, since it's not caused by smrpg, sorry!
