### ISSUE TITLE
csgo

### ISSUE THREAD

**Issue by hackers4win** [peace-maker/smrpg#299]
my server got banned for this plugin :O

**Comment by Nobody-x** [comment]
Hi, it's not possible since the plugin is fully working with `"FollowCSGOServerGuidelines" "yes"`

**Comment by hackers4win** [comment]
hmm thats weird server got down when i put in this on the server :S

**Comment by Nobody-x** [comment]
Did you have some errors in the sourcemod logs?

**Comment by hackers4win** [comment]
L 10/15/2018 - 20:46:50: [SM] Failed to load plugin "upgrades\smrpg_upgrade_fastreload.css.smx": This plugin is for CS:S only..
L 10/15/2018 - 20:46:51: [SM] Failed to load plugin "upgrades\smrpg_upgrade_poisonsmoke.cstrike.smx": This plugin is for use in Counter-Strike games only. Bad engine version 12..
L 10/15/2018 - 20:46:51: [SM] Failed to load plugin "upgrades\smrpg_upgrade_shrinking.smx": CS:GO models don't support scaling properly :(.
only these 3

**Comment by Nobody-x** [comment]
OK, then is your account is banned for 1 month? If not, your server is not banned.

If your server is not banned, try to remove smrpg_upgrade_fastreload.css.smx, smrpg_upgrade_poisonsmoke.cstrike.smx and smrpg_upgrade_shrinking.smx. Then restart the server.

**Comment by hackers4win** [comment]
[https://cdn.discordapp.com/attachments/471439972067442689/501464915509248030/Screenshot_20181015-204151_Snapchat.jpg](url)

**Comment by hackers4win** [comment]
https://cdn.discordapp.com/attachments/471439972067442689/501464915509248030/Screenshot_20181015-204151_Snapchat.jpg

**Comment by Nobody-x** [comment]
Ok so your server (and your account for 1 month) is banned. Nothing to do with smrpg I think. I suppose you taken some free plugins for weapons' skins. 

We can't help you. All you need to do is make a new account, then buy the game again. And don't edit in the future `"FollowCSGOServerGuidelines"`, It will prevent your account to be banned :)
