### ISSUE TITLE
Counter strike source poison smoke no make damage.

### ISSUE THREAD

**Issue by srpg** [peace-maker/smrpg#300]
Poisonsmoke no make damage on enemies, even they are inside the smoke, but smoke color is green. I don´t get any erros and i have newest version of the sm:rpg.

**Comment by coty9090** [comment]
same is happening to my server. enemies don't take any damage.

Metamod:Source version 1.10.7-dev
SourceMod 1.9.0.6269
windows

**Comment by peace-maker** [comment]
That's been a typo introduced in https://github.com/peace-maker/smrpg/commit/97b619801bb3a65780d3997825d7dc6064fd59e9
Thanks for the report!
