### ISSUE TITLE
Exception reported: Handle 5aeb0b5d is invalid

### ISSUE THREAD

**Issue by fkMain** [peace-maker/smrpg#302]
[SM] Exception reported: Handle 5aeb0b5d is invalid (error 3)
[SM] Blaming: smrpg_effects.smx
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 248, /home/travis/build/peace-maker/smrpg/build/addons/sourcemod/scripting/include/smlib/general.inc::ClearHandle
[2] Line 39, smrpg_effects/ignite.sp::ResetIgniteClient
[3] Line 107, smrpg_effects.sp::Event_OnPlayerDeath

**Comment by Z-RAY-Z** [comment]
I was got same error too.

**Comment by Hetachi** [comment]
Just checked logs, I am getting same error with newest stable sourcemod version.

**Comment by Master-GitHub** [comment]
Same problem

**Comment by ifrag-ru** [comment]
The same problem, because of this, the server can not fall? When do you hear about the update?

**Comment by peace-maker** [comment]
I failed to see the cause of this error when skimming through the code a week ago. I'll fire up a test server and try to replicate.

Does it happen on some special occasions?

**Comment by fkMain** [comment]
It always happen , all time errors in console

**Comment by paulocrash** [comment]
I'm having the same problem here: #303 and another I'm having too.

**Comment by peace-maker** [comment]
A quick fix is to set `mp_disconnect_kills_players 0` in your server.cfg. The `player_death` event now fires after `OnClientDisconnect` with that convar enabled which messes up the internal state of the plugins.

**Comment by peace-maker** [comment]
This is now fixed. Sorry for the delay, I didn't follow the changes in CS:GO updates.
