### ISSUE TITLE
Does not regenerate ammo CSGO

### ISSUE THREAD

**Issue by angels300** [peace-maker/smrpg#306]
After the upgrade, it stopped regenerating the cartridges, or rather, it does it very crookedly. There are no errors in the logs.

**Comment by angels300** [comment]
Please tell me the fixes

**Comment by peace-maker** [comment]
Are you using the latest gamedata?
https://github.com/peace-maker/smrpg/blob/master/gamedata/smrpg_resup.games.txt

**Comment by peace-maker** [comment]
Called the wrong function ☹️ This is fixed now.
