### ISSUE TITLE
not saved

### ISSUE THREAD

**Issue by TheReal28** [peace-maker/smrpg#31]
Hello today I restarted the server and rpg stopped to write to the database

L 06/19/2015 - 09:47:09: [smrpg/smrpg.smx] Error executing query: disk I/O error
L 06/19/2015 - 09:47:39: [smrpg/smrpg.smx] Error executing query 0 of 2 queries: disk I/O error

**Comment by peace-maker** [comment]
Nothing related directly to this plugin. Your hdd seems full?
