### ISSUE TITLE
Bug? smrpg_need_enemies "0" suicide gives XP

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#311]
Whenever a user kills themselves they get XP for suiciding.

**Comment by peace-maker** [comment]
Do you have the smrpg_cstrike plugin disabled?

**Comment by Hetachi** [comment]
Yes, plugin smrpg_cstrike is disabled on that server. I will test out the newest update and let you know if its fixed

**Comment by peace-maker** [comment]
> Also would it be possible to prevent XP gain in warmup ?

That's possible indeed. Check the new `smrpg_disable_experience_warmup` convar in smrpg_cstrike.
Please create seperate issues for different topics next time 😉
