### ISSUE TITLE
Danger zone xp for winning the round 1st, 2nd and 3rd place?

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#312]
Danger zone xp for winning the round 1st, 2nd and 3rd place?

Is there any plugin for this or anyone can make one ?

**Comment by peace-maker** [comment]
I suspect that information to be available in the new "SurvivalStats" usermessage - which we can't hook using sourcemod yet. We'll have to wait until the patches get merged into SourceMod itself before implementing it nicely.

**Comment by peace-maker** [comment]
Oh, I updated SourceMod one year ago, but didn't actually use it here. I've added 3 new convars to give experience to the top 3 players of a danger zone match in CS:GO. `smrpg_exp_dz_place_1`, smrpg_exp_dz_place_2` and `smrpg_exp_dz_place_3`.

Is this what you imagined?

**Comment by Hetachi** [comment]
> Oh, I updated SourceMod one year ago, but didn't actually use it here. I've added 3 new convars to give experience to the top 3 players of a danger zone match in CS:GO. `smrpg_exp_dz_place_1`, smrpg_exp_dz_place_2`and`smrpg_exp_dz_place_3`.
> 
> Is this what you imagined?

Yes thank you for the update :D
