### ISSUE TITLE
Good day, adrenaline does not work on the csgo server

### ISSUE THREAD

**Issue by angels300** [peace-maker/smrpg#313]
Good day, adrenaline does not work on the csgo server, there are no errors in the logs.

**Comment by srpg** [comment]
It doesn´t work on cs:go. It is only counter strike source skill.

**Comment by peace-maker** [comment]
Are sure you're not confusing the effect with the Impulse upgrade? Their meanings are switched compared to THCRPG.

You should get a speed boost simply by shooting an enemy with adrenaline. Impulse gives speed to the victim who got shot.

What exactly is not working? It's a generic upgrade that should work on any game.

**Comment by angels300** [comment]
Adrenaline, when shooting should accelerate

**Comment by peace-maker** [comment]
Works fine here. What's your `smrpg_adrenaline_hit_enemy` convar set to in the upgrade's config file?

**Comment by angels300** [comment]
smrpg_adrenaline_hit_enemy "1"

**Comment by angels300** [comment]
Sorry really works.
