### ISSUE TITLE
Exception reported: Handle 744606f9 is invalid (error 3)

### ISSUE THREAD

**Issue by Septembers** [peace-maker/smrpg#317]
L 01/19/2019 - 21:04:04: [SM] Exception reported: Handle 744606f9 is invalid (error 3)
L 01/19/2019 - 21:04:04: [SM] Blaming: rpg/smrpg_effects.smx
L 01/19/2019 - 21:04:04: [SM] Call stack trace:
L 01/19/2019 - 21:04:04: [SM]   [0] CloseHandle
L 01/19/2019 - 21:04:04: [SM]   [1] Line 248, C:\Users\September-PC\Desktop\COMPILE\scripting\include\smlib/general.inc::ClearHandle
L 01/19/2019 - 21:04:04: [SM]   [2] Line 39, smrpg_effects/ignite.sp::ResetIgniteClient
L 01/19/2019 - 21:04:04: [SM]   [3] Line 95, C:\Users\September-PC\Desktop\COMPILE\scripting\smrpg_effects.sp::Event_OnPlayerSpawn
L 01/19/2019 - 21:04:04: [SM]   [5] CS_RespawnPlayer
L 01/19/2019 - 21:04:04: [SM]   [6] Line 107, /home/forums/content/files/4/3/9/5/5/48030.attach::RespawnClient

**Comment by peace-maker** [comment]
Hm, I've never been able to reproduce this. Please reopen if this is still an issue.
