### ISSUE TITLE
Doubt with two Upgrades options

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#319]
`- Poison Smoke (Counter-Strike: Source only) - Damages players inside the smoke of a smoke grenade.`
I wonder if it would be possible to make a compatible version for the CSGO?

`- Shrinking - Make player models smaller.`
And this in case neither works in CSGO, would that be normal? Would it also be possible to make a compatible version for the CSGO?

**Comment by Hetachi** [comment]
There is already a issue with poison smoke for CS:GO #301

**Comment by peace-maker** [comment]
It's possible to make poisonsmoke for csgo, but the property to scale csgo models doesn't work properly. Only some parts of the model change the size while the others keep their height. That makes the models look really bad.

The poisonsmoke is tracked in another issue as @Hetachi pointed out.
