### ISSUE TITLE
How can i enable/disable each skill?

### ISSUE THREAD

**Issue by maxgraham** [peace-maker/smrpg#32]
Hello, sorry, but i don't know why there is no simple configuration option. I'm talking about "regen_enable "1" " or something like this. For ex. i wanna disable "speed" because i don't need it, but i don't know how. 

Can you please tell me? And also, how to put my ID to the admin list?

Thank you!

**Comment by maxgraham** [comment]
also, where can i set the default, starting credit? And the cost of each skill and the plus cost for each new level skill?

**Comment by peace-maker** [comment]
All plugins generate config files in <game>/cfg/sourcemod/smrpg.
There is a general config file in <game>/cfg/sourcemod/plugin.smrpg.cfg to change the starting credits and all the other options.

If you want to disable upgrades completely, it's best to not load them in the first place. Just remove the corresponding smrpg_upgrade_speed.smx plugin.

Currently the admin commands require the root "z" flag by default.
