### ISSUE TITLE
SQLite problem

### ISSUE THREAD

**Issue by nanociaglia** [peace-maker/smrpg#323]
[RPG\smrpg.smx] Unable to insert player info (column steamid is not unique)
[RPG\smrpg.smx] Unable to insert player info (column steamid is not unique)
[RPG\smrpg.smx] Unable to insert player info (column steamid is not unique)
[RPG\smrpg.smx] Unable to insert player info (column steamid is not unique)

This error was spammed a lot of times in my error logs, and some players lost their saved data, they had to reconnect to the server or wait until the map changes to get they levels/exp, etc again.

**Comment by peace-maker** [comment]
Without any way to reproduce this, it's impossible to debug. Closing this for now. Feel free to reopen if you encounter it again and have more info.
