### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by xeeek** [peace-maker/smrpg#327]
https://crash.limetech.org/rdt2utz4hp2t

**Comment by peace-maker** [comment]
Thank you, I've updated the gamedata. There were two functions matching the old signature now and we were targeting the second match.

**Comment by Z-RAY-Z** [comment]
^this guy provide incredibly amount of info :D
I was suffer from this crash too. Only **smrpg_enable 0** stop server from crashing.
I running **Metamod:Source 1.11.0-dev+1128** and **SourceMod 1.9.0.6282** /w standart bunch of the SM:RPG upgrades.
I was also try to launch server with **-nosse4** and this didn't help.

**Comment by peace-maker** [comment]
Do you still have issues? The Resupply `smrpg_upgrade_resup.smx` upgrade seems to be the problem on linux, since it's the only plugin that's using a `SDKCall` in smrpg. Windows is fine.

**Comment by Z-RAY-Z** [comment]
I was send my report in one time with you reply :D
Thank you for update, all works fine.

**Comment by peace-maker** [comment]
Ah, perfect timing I guess 😄
