### ISSUE TITLE
Speed+ don't work

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#328]
After recent update i discover that's Speed+ upgrade not working.
I using SourceMod (1.9.0.6282) and Metamod:Source 1.11.0-dev+1128
I was try update gamedata and find GetPlayerMaxSpeed via https://asherkin.github.io/vtable/ from server_i486.so but didn't sucsessed.

**Comment by peace-maker** [comment]
Which game? I checked the offset in CS:GO and it's still fine.

**Comment by Z-RAY-Z** [comment]
CS:GO. Players have talk about Speed+ wierd work.
I was up Speed+ for myself and didn't see any changes with my speed.
I think, this cause by some other plugins, there are modify wlak speed.
