### ISSUE TITLE
How do you even install this?

### ISSUE THREAD

**Issue by D4YN3X** [peace-maker/smrpg#33]
I am really amazed by seeing servers running this and it looks so customize able, but I have no idea how you do install it...
I am not very good at this programming/modding stuff but I know how to install normal plugins, but this I get no install location to the AutoexecConfig, where to put the #include <smlib> what is the plugin file? where is it located?
Could you make a idiot proof guide how to do?
Plz I have putted everything inside the sourcemod as it should be. Then I compiled the optional features and upgrades but get some errors/warnings with some of them.
So now where to put the upgrades in? in same as the other smx file or in another directory? IDK...
Help this looks so awesome and well made, I don't understand anything :/:/:/

**Comment by kalle4000** [comment]
I will gladly try to make such a guide, wait a little week or so :)

**Comment by peace-maker** [comment]
@kalle4000 You're welcome to create a new page in the wiki :)

**Comment by peace-maker** [comment]
Might as well leave a reference to #78 here.

**Comment by freaky1** [comment]
No noob proof guide :D?
