### ISSUE TITLE
Client 2 is not in game error

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#332]
Hello, i was get:
L 02/14/2020 - 08:11:37: [SM] Blaming: upgrades/smrpg_upgrade_regen.smx
L 02/14/2020 - 08:11:37: [SM] Call stack trace:
L 02/14/2020 - 08:11:37: [SM]   [0] IsPlayerAlive
L 02/14/2020 - 08:11:37: [SM]   [1] Line 113, upgrades/smrpg_upgrade_regen.sp::Timer_IncreaseHealth
L 02/14/2020 - 08:11:37: [SM] Exception reported: Client 2 is not in game

"SM:RPG Upgrade > Health regeneration" (1.0-532) by Jannik "Peace-Maker" Hartung
SourceMod (1.10.0.6462) by AlliedModders LLC

**Comment by WanekWest** [comment]
[smrpg_upgrade_regen.txt](https://github.com/peace-maker/smrpg/files/4208918/smrpg_upgrade_regen.txt)
Change txt to smx and upload it to server. That error will be fixed

**Comment by Bara** [comment]
If you modified the source, you also should provide the .sp-file too.

**Comment by WanekWest** [comment]
[smrpg_upgrade_regen.sp.txt](https://github.com/peace-maker/smrpg/files/4208955/smrpg_upgrade_regen.sp.txt)
Yup,sorry.

**Comment by peace-maker** [comment]
Thanks, fixed.
