### ISSUE TITLE
Client 3 is not in game

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#333]
Hello, i was encounter rare errors in logs:
L 02/27/2020 - 13:40:21: [SM] Exception reported: Client 3 is not in game
L 02/27/2020 - 13:40:21: [SM] Blaming: upgrades/smrpg_upgrade_armorregen_cstrike.smx
L 02/27/2020 - 13:40:21: [SM] Call stack trace:
L 02/27/2020 - 13:40:21: [SM]   [0] IsPlayerAlive
L 02/27/2020 - 13:40:21: [SM]   [1] Line 125, upgrades/smrpg_upgrade_armorregen_cstrike.sp::Timer_IncreaseArmor

"SM:RPG Upgrade > Armor regeneration" (1.0-532) by Jannik "Peace-Maker" Hartung
SourceMod (1.10.0.6474) by AlliedModders LLC

**Comment by peace-maker** [comment]
Thanks!
