### ISSUE TITLE
[Question/Request] convar for round winning team that awards XP.

### ISSUE THREAD

**Issue by avarishd** [peace-maker/smrpg#335]
Trying to figure out if there is (or not) convar that awards the winning team XP, idea for using it in HNS server.
Cheers, also great work <3

Edit: to clarify its for when the timer runs out and the terrorist/hiders wins (due to HNS).

**Comment by peace-maker** [comment]
Check out the list of convars for config options.
https://github.com/peace-maker/smrpg/wiki/ConVar-list#smrpg-core

You might be interested in `smrpg_exp_teamwin` and possibly disable `smrpg_exp_use_teamratio`, since the team sizes are unbalanced in HNS.

You might want to disable the AFK check too, as hiders tend to not move.

Thanks :)

**Comment by avarishd** [comment]
@peace-maker 
Actually after reading all convars/playing around with it it doesn't seem that there is an actually convar that awards the winning team of the round for just surviving(timer running out).

You are warded for doing any of the following in the **smrpg_cstrike** but there isn't anything regarding round winning without doing any of the objectives. (Tested all of the smrpg_cstrike cvars and yes, they work flawlessly, only issue is the thing i'm explaining.)
Or perhaps i am missing something major?

Sorry for bothering you again... ;[

**Comment by peace-maker** [comment]
You are right, that convar discards "normal" wins by timeouts or killing the other team.
https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg_cstrike.sp#L362-L369

We could include more reasons into that list like `CSRoundEnd_CTWin` and `CSRoundEnd_TerroristWin`. That would be a behavior change for other users though, but I think it won't be much of an impact.

https://sm.alliedmods.net/new-api/cstrike/CSRoundEndReason

**Comment by peace-maker** [comment]
Set the new `smrpg_exp_non_objective_teamwin` convar in smrpg_cstrike to 1 to enable giving XP for just winning the round.
