### ISSUE TITLE
Errors with smrpg_antisuicide.smx

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#336]
I was discover that some malicious players do disconnect from server on low hp and return - they don't want enemy have EXP for kill.
I was try set mp_disconnect_kills_players to 1 - abusers disconnect from fight, got killed and lose some EXP.
But i got some errors:
L 03/29/2020 - 00:53:52: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 03/29/2020 - 00:53:52: [SM] Blaming: smrpg_antisuicide.smx
L 03/29/2020 - 00:53:52: [SM] Call stack trace:
L 03/29/2020 - 00:53:52: [SM]   [0] ArrayList.Length.get
L 03/29/2020 - 00:53:52: [SM]   [1] Line 89, smrpg_antisuicide.sp::Event_OnPlayerDeath

SM:RPG > Anti-Selfkill" (1.0-532) by Peace-Maker, SourceMod 1.10.0.6478

**Comment by peace-maker** [comment]
Meh, the order of events seems to have changed again since that initial bug #302 
I don't have time to debug this week, feel free to check it out yourself!

**Comment by peace-maker** [comment]
Ah, this is already fixed in the issue I linked above. SMRPG 1.0-532 is too old and doesn't include that fix yet.
