### ISSUE TITLE
icestab cage don't disappear in new rounds

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#338]
Hello, after search and adding missing effect-textures i got this;
![20191009174558_1](https://user-images.githubusercontent.com/42438717/78696976-d183da80-7908-11ea-835a-a7cca1c34c51.jpg)
This effects will keep forever untill map change. SM error logs are clean.
I use stock unmodifed SM:RPG Upgrade > Ice Stab" (1.0-552) and SourceMod (1.10.0.6478)
P.S. I think, you forgot add some textures in pack. CS:GO didn't have some textures shipped like CS:S.

**Comment by peace-maker** [comment]
hm, I tried to use different materials that are available in the different games in the sharedmaterials gamedata file. We should switch to a different one then, if csgo lacks the current one now.

Not sure about the effect staying forever. Any errors?

**Comment by peace-maker** [comment]
The cage effect should only stay there for a third of the actual freeze time. Do you have the icestab level at some high max level?

https://github.com/peace-maker/smrpg/blob/master/scripting/upgrades/smrpg_upgrade_icestab.sp#L182-L183

**Comment by peace-maker** [comment]
The selected materials are still bundled in CS:GO, at least on my server.

https://github.com/peace-maker/smrpg/blob/master/gamedata/smrpg_sharedmaterials.games.txt#L33-L41

What makes you think you needed to touch anything?

**Comment by Z-RAY-Z** [comment]
> Do you have the icestab level at some high max level?
I was check DB and found noone had Icestab in maximum level.
Cvars: smrpg_icestab_maxlevel "15" and smrpg_icestab_inc "0.135"

> Not sure about the effect staying forever. Any errors?
I didn't see any errors in SM logs.

> The selected materials are still bundled in CS:GO, at least on my server.
I was no see cage effect for a long time, i was try investigate which textures this module use, found & put them and after that cage-effect start working.

> We should switch to a different one then, if csgo lacks the current one now.
You can pack missing materials what you like in release packages.

**Comment by peace-maker** [comment]
This seems to be a problem with tempents in csgo, which I can't really control in the plugin since they are purely clientside. I've heard sending a `round_start` event causes all effects to disappear in csgo, but your problem seems to be something else since it happens after a new round started.. I'll close this now as WONTFIX, since it's a clientside problem. The cage effect works for me right out the box without any extra materials, so not sure what your setup was.
