### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by Szarak2004** [peace-maker/smrpg#341]
Can I please get the default value of:
Vampire:
Starting Cost;
Increase Cost;
Somebody changed them and I need the defaults

**Comment by Hetachi** [comment]
https://github.com/peace-maker/smrpg/blob/master/scripting/upgrades/smrpg_upgrade_vampire.sp

**Comment by peace-maker** [comment]
It should already tell you in the comments above the option in the config file or you could rename/delete the old config file and reload the plugin to recreate the config file with the defaults.

Starting cost defaults to 15 increasing by 10 each level.
