### ISSUE TITLE
rpgmenu_sorting Doesn't work

### ISSUE THREAD

**Issue by bbbird5** [peace-maker/smrpg#343]
I changed the rpgmenu_sorting.txt file, but when I typed in the game! Rpg, the upgrade menu remained unchanged
![image](https://user-images.githubusercontent.com/63526710/82718862-e01b2b00-9cd7-11ea-965d-ed9fe6614205.png)

Am I correct in this way? What should I modify if it is incorrect

**Comment by peace-maker** [comment]
That file is only for sorting the entries in the menu. You have to add the lines similar to the other entries in the file

```
"RPGUpgradesMenu"
{
    "item" "rpgupgrade_damage"
}
```

If you want to change the name of the upgrade you can translate it using sourcemod's translation system by modifying the smrpg.phrases.txt file of your language or creating a new one.
