### ISSUE TITLE
Denial upgrade bug

### ISSUE THREAD

**Issue by cyziek** [peace-maker/smrpg#345]
I have a bug on my server with denial upgrade.
For example: 2 players has AKs and Player A killed Player B. Player B who dies, has restored weapon in next round and players A who kills has no weapon in next round. In should works the other way round.

**Comment by Hetachi** [comment]
This is again not a bug but how denial works... If you die your weapons are brought back to you. By default CS:GO does not remove your weapons if you survive a round.

**Comment by cyziek** [comment]
Ok but if I kill somebody (i have denial upgraded) In next round i don't have my gun, and player who dies in next round has wepon(but he shouldn't have).

**Comment by peace-maker** [comment]
Are you sure the other player doesn't have the Denial upgrade as well?
What game mode are you running your server in? @Hetachi is right, the game lets you keep your weapons into the next round if you didn't die, so the plugin doesn't do anything if you survived the round.

**Comment by cyziek** [comment]
I fixed problem. The problem was command in server cfg
mp_equipment_reset_rounds 1
I used it to fix bug in HUD becasue I had two or three knives.
Now i deleted this and working properly.
