### ISSUE TITLE
Upgrades affecting other players no longer working

### ISSUE THREAD

**Issue by Lexi2997** [peace-maker/smrpg#349]
Since the newest CSGO update, upgrades such as Impulse, Vampire, Damage, Ice Stab, Fire/Frost Pistol, Fire/Frost Grenade have stopped working entirely. These are the ones we've tested that don't work, and it seems to be that it's just upgrades that are triggered by other players that have stopped working. 

Is this another case of the CSGO update breaking RPG or is something else causing these issues?

**Comment by peace-maker** [comment]
That sounds like an issue with the changed CTakeDamage class in csgo which is currently being fixed in SourceMod.

So updating SourceMod should fix the issue once it gets sorted there. Let me know if there are still issues persistent.

**Comment by Lexi2997** [comment]
The newest SourceMod update fixed this issue completely. Thanks for the advice!
