### ISSUE TITLE
A way to disable specific/all upgrades, on different map types

### ISSUE THREAD

**Issue by mikcla** [peace-maker/smrpg#351]
I whould like if i chould make a server were there were different map types. Fx Ba_jail, surf, MiniGame, knife fight and so on...
But fx on the knife fight map, i whould like to disable all upgrades, but players should still get exp and levels. But when the map changes to fx dust 2 i whould like it all to be back.
I now only a little code, and almost nothing when it comes to codeing in source, but i have an idea how it should be. There should be some bools the cover different map types, and when you join fx a Ba_jail map, there should be a script that simply turns the bool  Ba_jail true. There should be a cfg where pepole can make there own maps bools, and they should put maps into there catogeris, proberly in different folders. In the cfg you should also say what upgrades should be turned off and on, just like the cfg right now, but in different map types.
I whould be very thankful if you chould make this <3

**Comment by peace-maker** [comment]
You can use map configs to execute a config file on a certain map and unload the upgrade plugins you don't want in those files. For example add the following line to the ba_jail.cfg to remove the health upgrade for that map.

`sm plugins unload smrpg/smrpg_upgrade_health` or `smrpg_health_enable 0`

You can put the upgrades in the `plugins/optional` folder to prevent SourceMod from loading them automatically. Then you can add map configs to explicitly load the upgrades you want similar to the way described above.

I don't think this requires any code changes and can be done entirely using available means and configuration options.

**Comment by mikcla** [comment]
Thank you very much, i haven't tried to do all the things you have said yet, but i wont be long to i begin
