### ISSUE TITLE
Client is not connected

### ISSUE THREAD

**Issue by Septembers** [peace-maker/smrpg#352]
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not connected
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_damage.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] IsFakeClient
L 08/26/2020 - 09:54:40: [SM]   [1] Line 111, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_damage.sp::Hook_OnTakeDamage
L 08/26/2020 - 09:54:40: [SM] Exception reported: Callback-provided entity 14 for attacker is invalid
L 08/26/2020 - 09:54:40: [SM] Blaming: shop.smx::Hook_OnTakeDamage
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not connected
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_bouncybullets.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] IsFakeClient
L 08/26/2020 - 09:54:40: [SM]   [1] Line 137, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_bouncybullets.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not in game
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_impulse.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] GetClientTeam
L 08/26/2020 - 09:54:40: [SM]   [1] Line 176, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_impulse.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not in game
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_adrenaline.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] GetClientTeam
L 08/26/2020 - 09:54:40: [SM]   [1] Line 151, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_adrenaline.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not connected
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_firepistol.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] IsFakeClient
L 08/26/2020 - 09:54:40: [SM]   [1] Line 116, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_firepistol.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not connected
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_fpistol.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] IsFakeClient
L 08/26/2020 - 09:54:40: [SM]   [1] Line 168, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_fpistol.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not connected
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg_upgrade_vampire.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] IsFakeClient
L 08/26/2020 - 09:54:40: [SM]   [1] Line 115, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg_upgrade_vampire.sp::Hook_OnTakeDamagePost
L 08/26/2020 - 09:54:40: [SM] Exception reported: Client 14 is not in game
L 08/26/2020 - 09:54:40: [SM] Blaming: smrpg/smrpg.smx
L 08/26/2020 - 09:54:40: [SM] Call stack trace:
L 08/26/2020 - 09:54:40: [SM]   [0] GetClientTeam
L 08/26/2020 - 09:54:40: [SM]   [1] Line 339, smrpg/smrpg_stats.sp::Stats_PlayerDamage
L 08/26/2020 - 09:54:40: [SM]   [2] Line 494, C:\Users\September-PC\Desktop\COMPILE 1.10 10\smrpg.sp::Hook_OnTakeDamagePost

SourceMod Version: 1.10.0.6492

**Comment by peace-maker** [comment]
Which game? A player getting attacked after disconnecting sounds like a game bug.

**Comment by Septembers** [comment]
> Which game? A player getting attacked after disconnecting sounds like a game bug.

cs:go

**Comment by peace-maker** [comment]
Oh, it's the attacker disconnecting before the damage was dealt. Probably some grenade exploding after the player disconnected or some other new way to deal damage after some time? What game mode are you running?

**Comment by Septembers** [comment]
> Oh, it's the attacker disconnecting before the damage was dealt. Probably some grenade exploding after the player disconnected or some other new way to deal damage after some time? What game mode are you running?

I can't tell you exactly when it appears. but this is often
casual game mode

**Comment by peace-maker** [comment]
Those errors should be fixed in the latest build. Thanks for the report!
