### ISSUE TITLE
Assist issue/suggestion

### ISSUE THREAD

**Issue by Koslii** [peace-maker/smrpg#355]
Hey, is there is a way to give an exact number of XP points on an assist? If not, could you consider adding it in a future update?

I am aware of the "Experience for hurting an enemy multiplied by the damage done". However, this doesn't work too well with the game-mode our server has. Currently, the server is without XP on kill, which leads to a quite unbalanced server.

**Comment by peace-maker** [comment]
There is `smrpg_exp_kill_assist`. Is that enough?

**Comment by Koslii** [comment]
Maybe, where can I find the cfg file for that?

**Comment by peace-maker** [comment]
https://github.com/peace-maker/smrpg/wiki/ConVar-list#smrpg_cstrike-counter-strike-experience-module
It's in the plugin.smrpg_cstrike.cfg

**Comment by peace-maker** [comment]
I guess it was enough.
