### ISSUE TITLE
sm:rpg stats

### ISSUE THREAD

**Issue by Balkony** [peace-maker/smrpg#358]
Hello.I install sm:rpg plugin,and i want to reset all pleyer stats ,im tryed to reset stats whith this plugin.smrpg_resetstats.cfg config
but this not working . Who knows how reset all players stats ? (i mean how i can reset all pleyers sm:rpg level)

**Comment by peace-maker** [comment]
Check the wiki. You're probably looking for the `smrpg_resetstats` command.
https://github.com/peace-maker/smrpg/wiki/Admin-commands
