### ISSUE TITLE
How can i make smrpg_addcredits @all

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#36]
I want to add credits to all players of my server, but i dont know how 
Can you help me?

**Comment by peace-maker** [comment]
I intentionally didn't allow multi-target filters in the admin commands, so some admin couldn't do !smrpg_resetstats @all while being in a bad mood. Looking back, that reasoning seems silly now.

**Comment by vBDSK** [comment]
Can you give me fixed admin file() please, i want to have this function

**Comment by coty9090** [comment]
@ peace-maker: That's a decent reason, but why would you give admin to someone you know that has mood issues and can't be trusted to act civil? The @all/ct/t commands would be a very nice addition to smrpg...

**Comment by peace-maker** [comment]
I've added multi-target filter support now. Haven't tested it deeply, so there could still be output issues :P
