### ISSUE TITLE
bug with bouncybullets

### ISSUE THREAD

**Issue by Septembers** [peace-maker/smrpg#361]
I have limited repelling bullets on pistols
smrpg_bouncybullets_ignore_weapons "knife, p90, bizon, cz75a, deagle, elite, fiveseven, glock, hkp2000, p250, revolver, tec9, usp_silencer"

But if you pump the ability "firepistol", then bounce bullets starts working on pistols again.
I am using the latest version of the plugin
sorry for my english.

**Comment by peace-maker** [comment]
Thanks for the report, your english is fine! Have a try with the latest version please.

**Comment by Septembers** [comment]
> Thanks for the report, your english is fine! Have a try with the latest version please.

open please issues #354
sorry for offtopic

**Comment by Septembers** [comment]
bug fixed, thx
