### ISSUE TITLE
Credits not spent when purchasing upgrades

### ISSUE THREAD

**Issue by andylfc19931993** [peace-maker/smrpg#366]
When anyone buys an upgrade the credit total they have does not go down. This is the error message that appears in the log:

L 03/13/2021 - 21:35:30: [SM] Blaming: smrpg.smx
L 03/13/2021 - 21:35:30: [SM] Call stack trace:
L 03/13/2021 - 21:35:30: [SM]   [0] Call_StartFunction
L 03/13/2021 - 21:35:30: [SM]   [1] Line 546, smrpg/smrpg_players.sp::SetClientSelectedUpgradeLevel
L 03/13/2021 - 21:35:30: [SM]   [2] Line 598, smrpg/smrpg_players.sp::GiveClientUpgrade
L 03/13/2021 - 21:35:30: [SM]   [3] Line 626, smrpg/smrpg_players.sp::BuyClientUpgrade
L 03/13/2021 - 21:35:30: [SM]   [4] Line 254, smrpg/smrpg_menu.sp::TopMenu_HandleUpgrades

Upgrade was given, but no credits were taken. Any ideas?

**Comment by peace-maker** [comment]
Above that stack trace should be the actual error message, which is needed to understand the problem. Could you please check if you missed a line?

**Comment by andylfc19931993** [comment]
Hey peace-maker, thanks for your response.

L 03/14/2021 - 00:02:01: [SM] Exception reported: Invalid function id (FFFFFFFF)
L 03/14/2021 - 00:02:01: [SM] Blaming: smrpg.smx
L 03/14/2021 - 00:02:01: [SM] Call stack trace:
L 03/14/2021 - 00:02:01: [SM]   [0] Call_StartFunction
L 03/14/2021 - 00:02:01: [SM]   [1] Line 546, smrpg/smrpg_players.sp::SetClientSelectedUpgradeLevel
L 03/14/2021 - 00:02:01: [SM]   [2] Line 598, smrpg/smrpg_players.sp::GiveClientUpgrade
L 03/14/2021 - 00:02:01: [SM]   [3] Line 626, smrpg/smrpg_players.sp::BuyClientUpgrade
L 03/14/2021 - 00:02:01: [SM]   [4] Line 254, smrpg/smrpg_menu.sp::TopMenu_HandleUpgrades
Terrorist bot spawned outside of a buy zone (-654, 3550, 43)
L 03/14/2021 - 00:02:16: [SM] Exception reported: Invalid function id (FFFFFFFF)
L 03/14/2021 - 00:02:16: [SM] Blaming: smrpg.smx
L 03/14/2021 - 00:02:16: [SM] Call stack trace:
L 03/14/2021 - 00:02:16: [SM]   [0] Call_StartFunction
L 03/14/2021 - 00:02:16: [SM]   [1] Line 546, smrpg/smrpg_players.sp::SetClientSelectedUpgradeLevel
L 03/14/2021 - 00:02:16: [SM]   [2] Line 598, smrpg/smrpg_players.sp::GiveClientUpgrade
L 03/14/2021 - 00:02:16: [SM]   [3] Line 626, smrpg/smrpg_players.sp::BuyClientUpgrade
L 03/14/2021 - 00:02:16: [SM]   [4] Line 733, smrpg/smrpg_players.sp::BotPickUpgrade
L 03/14/2021 - 00:02:16: [SM]   [5] Line 209, smrpg/smrpg_stats.sp::Stats_PlayerNewLevel
L 03/14/2021 - 00:02:16: [SM]   [6] Line 309, smrpg/smrpg_stats.sp::Stats_AddExperience
L 03/14/2021 - 00:02:16: [SM]   [7] Line 534, smrpg/smrpg_stats.sp::Native_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [9] SMRPG_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [10] Line 490, C:\Users\Fran\Desktop\sm\smrpg-master\scripting\smrpg_cstrike.sp::Debug_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [11] Line 259, C:\Users\Fran\Desktop\sm\smrpg-master\scripting\smrpg_cstrike.sp::Event_OnPlayerHurt
L 03/14/2021 - 00:02:16: [SM] Exception reported: Invalid function id (FFFFFFFF)
L 03/14/2021 - 00:02:16: [SM] Blaming: smrpg.smx
L 03/14/2021 - 00:02:16: [SM] Call stack trace:
L 03/14/2021 - 00:02:16: [SM]   [0] Call_StartFunction
L 03/14/2021 - 00:02:16: [SM]   [1] Line 546, smrpg/smrpg_players.sp::SetClientSelectedUpgradeLevel
L 03/14/2021 - 00:02:16: [SM]   [2] Line 598, smrpg/smrpg_players.sp::GiveClientUpgrade
L 03/14/2021 - 00:02:16: [SM]   [3] Line 626, smrpg/smrpg_players.sp::BuyClientUpgrade
L 03/14/2021 - 00:02:16: [SM]   [4] Line 733, smrpg/smrpg_players.sp::BotPickUpgrade
L 03/14/2021 - 00:02:16: [SM]   [5] Line 209, smrpg/smrpg_stats.sp::Stats_PlayerNewLevel
L 03/14/2021 - 00:02:16: [SM]   [6] Line 309, smrpg/smrpg_stats.sp::Stats_AddExperience
L 03/14/2021 - 00:02:16: [SM]   [7] Line 534, smrpg/smrpg_stats.sp::Native_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [9] SMRPG_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [10] Line 490, C:\Users\Fran\Desktop\sm\smrpg-master\scripting\smrpg_cstrike.sp::Debug_AddClientExperience
L 03/14/2021 - 00:02:16: [SM]   [11] Line 314, C:\Users\Fran\Desktop\sm\smrpg-master\scripting\smrpg_cstrike.sp::Event_OnPlayerDeath

Here's the whole thing that generates in log. Is it the invalid function message you were looking for?

**Comment by andylfc19931993** [comment]
Hey,

Just thought I'd let you know I've fixed this. Was a compile issue, something had gone wrong. Re-compiled and all is well.
