### ISSUE TITLE
How to sort correctly in the skill menu?

### ISSUE THREAD

**Issue by xeeek** [peace-maker/smrpg#372]
How to sort correctly in the skill menu? I'm editing a file rpgmenu_sorting.txt, I add the lines from the skills there, but the sorting does not work. Can you give an example of what the skill item should look like in the file for sorting?

**Comment by peace-maker** [comment]
The format is described at the top of the file. How did you add the lines? Something like this should work.

```
"Menu"
{
	"RPGUpgradesMenu"
	{
		"item" "rpgupgrade_health"
		"item" "rpgupgrade_regen"
	}

	...
}
```

**Comment by peace-maker** [comment]
I assume this is resolved.
