### ISSUE TITLE
Not working strings

### ISSUE THREAD

**Issue by Blueberryy** [peace-maker/smrpg#374]
"RPG menu sell upgrade entry show max" has {4} ("Sale") that **should** be translateable but itsn't
"RPG menu upgrade settings entry level selection" has {4} ("Off" or "On") that **should** be translateable but itsn't
"Level Chat Tag" just won't work on other players(like it works with only client messages)

**Comment by peace-maker** [comment]
Hm, which game and SourceMod version? I can't reproduce this (testing with german instead of russian) :(
Which chat processor do you use too?

**Comment by Blueberryy** [comment]
Will re-open issue when get to it again.
