### ISSUE TITLE
Import xp from thc_rpg

### ISSUE THREAD

**Issue by ElCurioso** [peace-maker/smrpg#38]
Lots of server admins want to switch to smrpg. But on the other hand don´t want to loose their databases with *hard worked for* xp from thc_rpg.

It makes smrpg a lot more attractive: An import function.

Would be a great thing to have, since an import-plugin is definitively missing!

**Comment by peace-maker** [comment]
Uh, i'll see what i can do. This wasn't intended as a successor to thcrpg, so i don't know if we can safely merge the databases. SM:RPG has different upgrades, so players might would have picked their upgrades differently, if they had access to the new upgrades by the time.

**Comment by ElCurioso** [comment]
I see. Seems to be a challenge.

Just an idea (don´t know if it is possible):

Maybe "resetting" the old upgrades for old XP. So there would be only "old" XP to import in "new" XP.
With the "new" XP everyone could buy the "new" (sometimes different) upgrades - without starting from zero?

**Comment by peace-maker** [comment]
Try that plugin please. It adds a sm_importrpgdb admin command. Your smrpg database has to be empty for this to work and you should have configured smrpg correctly beforehand. Especially the smrpg_credits_start and smrpg_credits_inc convars as all player's credits will be reset to the amount they'd have on their level. They can choose new upgrades then.

**Comment by ElCurioso** [comment]
Ok, first problem (solved): new created database was never empty on server-start because of bots. "bot_join_after_player 1" did do the trick.

Second problem:

********************************
sm_importrpgdb
Can't import Ted. "BOT_Ted" is not a valid steamid.
Can't import Victor. "BOT_Victor" is not a valid steamid.
Can't import Eric. "BOT_Eric" is not a valid steamid.
Can't import Vinny. "BOT_Vinny" is not a valid steamid.
.
.
.
L 08/02/2015 - 11:47:29: [SM] Plugin encountered error 30: Script execution time
d out
L 08/02/2015 - 11:47:29: [SM] Displaying call stack trace for plugin "_smrpg_imp
ortrpgdb.smx":
L 08/02/2015 - 11:47:29: [SM]   [0]  Line 140, _smrpg_importrpgdb.sp::Cmd_Import
Database()

********************************

**Comment by peace-maker** [comment]
Ah thanks, i didn't know bots were saved like that. I'll convert them too. Could you send me a dump of your old database please?

**Comment by ElCurioso** [comment]
Sure thing :)
dump-file here:
http://www.file-upload.net/download-10813480/thc_rpg.sq3.html

error log with dump-file:

Going to import 39 players...
L 08/02/2015 - 16:38:36: [SM] Native "GetClientUserId" reported: Client index 0
is invalid
L 08/02/2015 - 16:38:36: [SM] Displaying call stack trace for plugin "_smrpg_imp
ortrpgdb.smx":
L 08/02/2015 - 16:38:36: [SM]   [0]  Line 149, _smrpg_importrpgdb.sp::Cmd_Import
Database()

**Comment by peace-maker** [comment]
OK, forgot about the server console.

**Comment by ElCurioso** [comment]
Awesome! You are my hero, peace-maker. 

Imported 13.200 RPG-Clients (took me about 50 Minutes lol)!

About 40 Clients were skipped due to error code: 
**** Error importing player: near "PureOwl": syntax error ****
Seems to happen when there is at least one questionmark in the name.

or error code:
**** unrecognized token:"}" ****
Stars ale also unrecognized:  ★

0,3% error-quota is nearly nothing. Just thought you might want to know.

Great job!

**Comment by peace-maker** [comment]
Oh, wtf. I didn't expect the database to be that large. I've modified the script to load the players in chunks of 100 players each, so it doesn't load the whole database in memory. This should speed things up.

The player name might have been a problem with utf8 characters getting fetched as latin1 ones. I've set the charset to utf8 now, which should fix the names.

**Comment by ElCurioso** [comment]
I played alound a little with "IMPORT_STEP".
Compiled with 5000, 100,10 and 1. The first three took about 40 min. and the 1_step 45 minutes to import 13.200 clients. But that´s no problem since you do it only once.

The problems with questionmarks in the names persist.
Here is a link with a dump rpg-database wich contains problematic names:
http://www.file-upload.net/download-10837330/thc_rpg.sq3.html

Only one guy with questionmarks is imported correctly (he has chinese letters between them).

**Comment by ElCurioso** [comment]
Importing is functioning, thats sooo great!
Two minor requests if you want to make your import-plugin more powerful:

1) "smrpg_player_expire" does not work properly with the imported clients (lastseen = 0). Maybe the date of importing could be set there?

2) About two third of the clients are below level 10. It would be highly apreciated to be able to skip those. E.g. with setting a minimum-level for importing.

**Comment by peace-maker** [comment]
Thanks for your suggestions. I've added them too. 
sm_importrpgdb now accepts an optional argument to set the minimum level of players to import.
This could still be improved by using threaded queries only and add multiple players with one INSERT VALUES (..),(..),(..) query.
