### ISSUE TITLE
[Upgrade Request] Conversion

### ISSUE THREAD

**Issue by DeewaTT91** [peace-maker/smrpg#387]
In Counter Strike there is little to none incentive to be conservative with your money when you are winning alot. At some point you will always have 16000$ and all the excess money goes to waste.
So how about a Skill called Conversion:

Conversion allows the player to turn excess money into credits. 
Lvl 1 Conversion turns every 100$ above 16000 into 1 exp
Lvl 2 Conversion turnst every 100$ (or could be changed depending on lvl to maybe 99) into 2(depending on level) exp
and so on.

**Comment by WanekWest** [comment]
Try this. On round start it will exchange.

To translate add: `Conversion`
[smrpg_upgrade_convertion.txt](https://github.com/peace-maker/smrpg/files/10578939/smrpg_upgrade_convertion.txt)

**Comment by DeewaTT91** [comment]
I tested it, but it does nothing. I also changed the value from 16000 to 12000 to check if there would be any impact, but it does neither add exp nor subtract money from the player.

**Comment by WanekWest** [comment]
> Try this.

[smrpg_upgrade_convertion.txt](https://github.com/peace-maker/smrpg/files/10713895/smrpg_upgrade_convertion.txt)

**Comment by DeewaTT91** [comment]
Thanks a ton for your effort! It didn't work right away, but I have edited it abit and now it works for the most part.

The one thing that doesn't work is resetting the clients money to 10000 (I changed it from 16000 to 10000 because I think we cannot really access any value above 16000).
So this function doesn't seem to work.

`
			SetEntProp(client, Prop_Send, "m_iAccount", 10000);
`
