### ISSUE TITLE
error in code "freeze.sp" while compiling

### ISSUE THREAD

**Issue by ElCurioso** [peace-maker/smrpg#39]
//// smrpg_effects.sp
//
// smrpg_effects/freeze.sp(6) : error 001: expected token: "-identifier-", but f
ound ";"
// smrpg_effects/freeze.sp(30) : error 029: invalid expression, assumed zero
// smrpg_effects/freeze.sp(32) : warning 217: loose indentation
// smrpg_effects/freeze.sp(154) : error 092: number of arguments does not match
definition
// smrpg_effects.sp(6) : warning 203: symbol is never used: "__unknown__"
//
// 3 Errors.

**Comment by coty9090** [comment]
you're not supposed to compile the .sp files in the smrpg_effects folder...

**Comment by peace-maker** [comment]
Which compiler version do you use?

**Comment by ElCurioso** [comment]
SourceMod Version Information:
   SourceMod Version: 1.7.2
   SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.2)
   SourcePawn API: v1 = 4, v2 = 6
   Compiled on: May 30 2015 05:09:24

**Comment by ElCurioso** [comment]
Great! Thank you for the hint. Problem solved.

I upgraded to the last stable Sourcemod-Version (1.7.3) and the error disappears.
 
***
SourceMod Version Information:
    SourceMod Version: 1.7.3-dev+5233
    SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5233)
    SourcePawn API: v1 = 4, v2 = 6
    Compiled on: Aug 18 2015 16:11:35
***

**Comment by peace-maker** [comment]
You might have used a different compiler version than the runtime on your server. The SM 1.7.0 compiler had some issues.
