### ISSUE TITLE
Regen does not accept float values for heal increase

### ISSUE THREAD

**Issue by DeewaTT91** [peace-maker/smrpg#392]
As the title states the 
`// Additional HP to regenerate each interval multiplied by level. (base + inc * (level-1))

// Default: "1"
// Minimum: "0.000000"
smrpg_regen_amount_inc "0.1"
`

does not accept values lower than 1

**Comment by peace-maker** [comment]
How do you envision this to work? Health is an integer, so setting the increment to 0.1 would truncate to 0 until level 10?

**Comment by DeewaTT91** [comment]
I wouldn't set it this low. I was just playing around with the values, but yes basically I want for one level to be less than 1 hp since there is also the interval that can be changed in the config. I want to have many levels (40+) for the skill but not have the player receive 40+ hp per second.

**Comment by DeewaTT91** [comment]
It is in the documentation aswell 
```

// Specify the base amount of HP which is regenerated at the first level.
// -
// Default: "1"
// Minimum: "0.100000"
```

**Comment by peace-maker** [comment]
Did you implement this yourself? Pull requests are very welcome!

**Comment by DeewaTT91** [comment]
Yes, Id love to make a pul request, but wasn't able to create a branch for your repository. I made a copy of it on my account and pushed the changes there. I invited you to check it out. Sorry if I got something wrong, this is the first time I am using this.
