### ISSUE TITLE
Native "GetClientHealth" reported: Client is not in game

### ISSUE THREAD

**Issue by PresidentEvil** [peace-maker/smrpg#40]
this was spamming the console when the server crashed:

L 08/19/2015 - 16:34:47: [SM] Displaying call stack trace for plugin "smrpg/smrpg_upgrade_regen.smx":
L 08/19/2015 - 16:34:47: [SM]   [0]  Line 123, C:\Users\Kevin\Downloads\addons\sourcemod\scripting\upgrades\smrpg_upgrade_regen.sp::Timer_IncreaseHealth()
L 08/19/2015 - 16:34:48: [SM] Native "GetClientHealth" reported: Client 8 is not in game

meta version
Metamod:Source version 1.10.5
Built from: https://github.com/alliedmodders/metamod-source/commit/e0ef546
Build ID: 939:e0ef546
Loaded As: Valve Server Plugin
Compiled on: May 30 2015
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

sm version
SourceMod Version Information:
SourceMod Version: 1.7.3-dev+5232
SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5232)
SourcePawn API: v1 = 4, v2 = 6
Compiled on: Aug 15 2015 17:19:08
Built from: https://github.com/alliedmodders/sourcemod/commit/e389f08
Build ID: 5232:e389f08
http://www.sourcemod.net/

ACCELERATOR:

Stack Trace
Function
0	server.so!CCSGameRules::IsSpawnPointValid(CBaseEntity*, CBasePlayer*) + 0x24
1	server.so!CCSPlayer::SelectSpawnSpot(char const*, CBaseEntity*&) + 0x19c
2	server.so!CCSPlayer::EntSelectSpawnPoint() + 0x318
3	server.so!CCSGameRules::GetPlayerSpawnSpot(CBasePlayer*) + 0x17
4	server.so!CBasePlayer::Spawn() + 0x2d1
5	server.so!CCSPlayer::Spawn() + 0xa1
6	server.so!CCSPlayer::RoundRespawn() + 0xa3
7	0xee5029c3
8	bintools.ext.so!CallWrapper::Execute(void*, void*) [CallWrapper.cpp:128 + 0xa]
9	cssdm.ext.2.csgo.so + 0x16580

another crash:

Stack Trace
Function
0	server.so!CCSGameRules::IsSpawnPointValid(CBaseEntity*, CBasePlayer*) + 0x24
1	server.so!CCSPlayer::SelectSpawnSpot(char const*, CBaseEntity*&) + 0x19c
2	server.so!CCSPlayer::EntSelectSpawnPoint() + 0x318
3	server.so!CCSGameRules::GetPlayerSpawnSpot(CBasePlayer*) + 0x17
4	server.so!CBasePlayer::Spawn() + 0x2d1
5	server.so!CCSPlayer::Spawn() + 0xa1
6	server.so!CCSPlayer::RoundRespawn() + 0xa3
7	0xecc189c3
8	bintools.ext.so!CallWrapper::Execute(void*, void*) [CallWrapper.cpp:128 + 0xa]
9	cssdm.ext.2.csgo.so + 0x16580

any idea why, first time I've seen this error, maybe its cause I updated to the latest SM? I compiled the plugins with the same SM version.

**Comment by peace-maker** [comment]
Hm, looks like a client is stuck in a bogous state while connecting. He's already authorized but takes a long time to actually join the server. The health regen plugin looks like it takes the assumption, that the player would be ingame by the time the database answered the query for the upgrade levels.

The actual crash seems to come from cssdm though. Trying to respawn the player before it is ingame.
When did that happen? What was happening on the server?

**Comment by PresidentEvil** [comment]
here is the last 10k of console before the crash, you can scroll to the bottom to see what happened before the server quit

http://pastebin.com/nsA35iMd

**Comment by peace-maker** [comment]
Do you still get this crash after updating smrpg?
