### ISSUE TITLE
smrpg_keyhint crash 

### ISSUE THREAD

**Issue by jffz** [peace-maker/smrpg#41]
SM 1.7.3
smrpg_keyhint is crashing the server when someone type rpgmenu.

Output : 
L 08/21/2015 - 10:43:11: [SM] Displaying call stack trace for plugin "smrpg_keyhint_info.smx":
L 08/21/2015 - 10:43:11: [SM]   [0]  Line 1786, /home/steam/steamcmd/master-rpgscout/csgo/addons/sourcemod/scripting/include/smlib/clients.inc::Client_PrintKeyHintTe
xt()
L 08/21/2015 - 10:43:11: [SM]   [1]  Line 164, smrpg_keyhint_info.sp::Timer_ShowInfoPanel()
L 08/21/2015 - 10:43:12: [SM] Native "PrintCenterText" reported: Could not send a usermessage
L 08/21/2015 - 10:43:12: [SM] Displaying call stack trace for plugin "deathmatch.smx":
L 08/21/2015 - 10:43:12: [SM]   [0]  Line 229, deathmatch/user_messages.sp::userMessage_MessageStructure_Print()
L 08/21/2015 - 10:43:12: [SM]   [1]  Line 239, deathmatch/user_messages.sp::userMessage_MessageStructure_Execute()
L 08/21/2015 - 10:43:12: [SM]   [2]  Line 545, deathmatch/user_messages.sp::userMessage_MessageQueueDisplay_Execute()
L 08/21/2015 - 10:43:12: [SM]   [3]  Line 621, deathmatch/user_messages.sp::userMessage_MessageQueue_Execute()
L 08/21/2015 - 10:43:12: [SM]   [4]  Line 862, deathmatch/user_messages.sp::userMessage_Worker()
L 08/21/2015 - 10:43:12: [SM] Native "StartMessage" reported: Unable to execute a new message, there is already one in progress
L 08/21/2015 - 10:43:12: [SM] Displaying call stack trace for plugin "smrpg_keyhint_info.smx":
L 08/21/2015 - 10:43:12: [SM]   [0]  Line 261, /home/steam/steamcmd/master-rpgscout/csgo/addons/sourcemod/scripting/include/usermessages.inc::StartMessageOne()
L 08/21/2015 - 10:43:12: [SM]   [1]  Line 1772, /home/steam/steamcmd/master-rpgscout/csgo/addons/sourcemod/scripting/include/smlib/clients.inc::Client_PrintKeyHintTe
xt()
L 08/21/2015 - 10:43:12: [SM]   [2]  Line 164, smrpg_keyhint_info.sp::Timer_ShowInfoPanel()
L 08/21/2015 - 10:43:13: [SM] Native "PrintCenterText" reported: Could not send a usermessage

**Comment by peace-maker** [comment]
You have to check the very first error during that time. All the other follow up errors are just a result of some code erroring after setting up a usermessage but before sending it.

**Comment by jffz** [comment]
it looks like the problem comes from a call to smlib made by your plugin, here is my config :
- sourcemod 1.7.3 dev5229
- SMLIB 0.9.7

**Comment by peace-maker** [comment]
Are you sure you're using that old smlib version? Get the latest snapshot from the git repository https://github.com/bcserv/smlib

Please paste the very first errors on top of the file before the spam starts.
