### ISSUE TITLE
FFA cvar

### ISSUE THREAD

**Issue by jffz** [peace-maker/smrpg#43]
IS it possible to add a FFA cvar ? 

I noticed that when a Terro kill a terro he'll not get XP. Even with mp_teammates_are_enemies 1

**Comment by peace-maker** [comment]
It's possible, but requires changes to all upgrades as well. They need to apply the effect to players in the same team too. Added in recent commit

**Comment by jffz** [comment]
Seems to not works or be buggy, could we talk on steam ?

**Comment by peace-maker** [comment]
What's not working? No experience for killing players in the same team?

**Comment by jffz** [comment]
Yup, no experience for killing ine the same team in deathmatch mode

**Comment by peace-maker** [comment]
You're testing on csgo, right?

**Comment by jffz** [comment]
yup

2015-11-09 12:29 GMT+01:00 peace-maker <notifications@github.com>:

**Comment by peace-maker** [comment]
I've finally come around to test this and it works as intended. Were you sure, you set smrpg_ffa 1 in plugin.smrpg.cfg?

**Comment by jffz** [comment]
Was due to "Deathmatch Goes Advanced" plugin


________________

BACHELOT *Geoffrey*
*Tel:* *+33 6 19 44 00 42 <%2B33%206%2019%2044%2000%2042>*
*Mail:* *bachelotg@gmail.com <bachelotg@gmail.com>*

2016-09-16 4:25 GMT+02:00 peace-maker <notifications@github.com>:
