### ISSUE TITLE
smrpg_menu.sp   -  Compilation aborted

### ISSUE THREAD

**Issue by ElCurioso** [peace-maker/smrpg#45]
SM 1.7.3, newest compiler.
New installed "smrpg-master.zip"

All smrpg*.sp files compile perfect, save one:

*******************************
//// smrpg_menu.sp
//
// smrpg_menu.sp(145) : error 017: undefined symbol "GetClientCredits"
// smrpg_menu.sp(171) : error 017: undefined symbol "MAX_UPGRADE_SHORTNAME_LENGT
H"
// smrpg_menu.sp(172) : error 163: indeterminate array size in "sizeof" expressi
on (symbol "sShortname")
// smrpg_menu.sp(174) : error 017: undefined symbol "InternalUpgradeInfo"
// smrpg_menu.sp(174) : error 009: invalid array size (negative, zero or out of
bounds)
// smrpg_menu.sp(174) : error 036: empty statement
// smrpg_menu.sp(174) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 7 Errors.
*******************************

**Comment by peace-maker** [comment]
The smrpg.sp includes all files in scripting/smrpg/smrpg_*.sp. Don't try to compile them individually.
