### ISSUE TITLE
Compiling issues 

### ISSUE THREAD

**Issue by blacksteve13** [peace-maker/smrpg#46]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// smrpg.sp
//
// G:\Servers\surf\cstrike\addons\sourcemod\scripting\include\smlib/entities.inc(26) : error 017: undefined symbol "IsValidEntity"
// G:\Servers\surf\cstrike\addons\sourcemod\scripting\include\smlib/entities.inc(26) : warning 215: expression has no effect
// G:\Servers\surf\cstrike\addons\sourcemod\scripting\include\smlib/entities.inc(26) : error 001: expected token: ";", but found ")"
// G:\Servers\surf\cstrike\addons\sourcemod\scripting\include\smlib/entities.inc(26) : error 029: invalid expression, assumed zero
// G:\Servers\surf\cstrike\addons\sourcemod\scripting\include\smlib/entities.inc(26) : fatal error 189: too many error messages on one line
//
// Compilation aborted.
// 4 Errors.
//
// Compilation Time: 0.95 sec
// ----------------------------------------

Press enter to exit ...

get this issue every time i try to compile

**Comment by jono666** [comment]
Use the latest version of smlib https://github.com/bcserv/smlib
