### ISSUE TITLE
health upgrade bug

### ISSUE THREAD

**Issue by jffz** [peace-maker/smrpg#47]
PLayer using this upgrade spawn with 100hp and then their hp grow.

**Comment by coty9090** [comment]
That sounds like deathmatch screwing it up. Do you run deathmatch? Or be a bit more specific...

**Comment by jffz** [comment]
Yup running "Deathmatch goes advanced" from hebus. Maybe you have any to fix it ?

**Comment by coty9090** [comment]
Disable deathmatch and see if that fixes it... If it does, usually deathmatch config lets you disable hp amount start. (like cssdm)

**Comment by jffz** [comment]
fixed it thanks =)
