### ISSUE TITLE
New patch broke speed module

### ISSUE THREAD

**Issue by Raritylicious** [peace-maker/smrpg#49]
Ever since the newest patch, speed upgrade module stopped working on CS:GO.
Can anyone take a look at it?

PS: However, the speed excelerator still works.

**Comment by peace-maker** [comment]
Grab the latest gamedata/smrpg_speed.games.txt. Haven't tested it, but should be fine.

**Comment by Raritylicious** [comment]
I just tested but still same :(

**Comment by peace-maker** [comment]
Ok, turns out i can't guess. Fetch the file again..
