### ISSUE TITLE
smrpg_db_resetdatabase need 2 params instead of 1

### ISSUE THREAD

**Issue by Nobody-x** [peace-maker/smrpg#50]
In the file

smrpg/scripting/**smrpg_resetstats.sp** at line **78**

this line chould be **if(args < 1)** instead of **if(args < 2)**. 

When we use the command we have this error 

`rcon smrpg_db_resetdatabase "test"`

`SM:RPG > Usage: smrpg_db_resetdatabase <reason>`

**Comment by peace-maker** [comment]
Thanks, fixed.
