### ISSUE TITLE
Stealth, Real Impulse and Mirror Damage

### ISSUE THREAD

**Issue by Nobody-x** [peace-maker/smrpg#52]
Hi,

I've rewritten the Stealth Upgrade to have a min alpha. Then when you specify the min alpha and the max level, Alpha reduce per level is calculated automaticaly.

I've also made a real impulse upgrade (from THC) the actual impusle is the Adrenalise upgrade of the THC (So my Impulse is when someone shot, he has a speed boost for x time)

And I've coded a Mirror Damage Upgrade. Like the one from THC too.

If you want I can send you my codes, all  based on your work.

**Comment by peace-maker** [comment]
Please create pull requests for every change you want to put in!
