### ISSUE TITLE
Possible CSGO freezing?

### ISSUE THREAD

**Issue by Raritylicious** [peace-maker/smrpg#53]
Does anyone has an issue where your server(s) would free/crash on mapchange/client connect,disconnect since new animation update?
or is it just me?

**Comment by peace-maker** [comment]
How is this related to this plugin?

**Comment by Raritylicious** [comment]
Sorry for not saying more clearly.
Eversince the new csgo update, smrpg would sometimes freeze my server on mapchange/client connect and disconnect.

But I'm not 100 percent sure wether if its smrpg or not so I opened this thread to hear from other users.

**Comment by peace-maker** [comment]
Do you have [Accelerator](https://forums.alliedmods.net/showthread.php?t=146644) installed to easily check where your server crashes?

**Comment by Raritylicious** [comment]
I'll try that extension and see if I can get any related crash logs and post them here.

**Comment by Raritylicious** [comment]
It was related to dbi.mysql.ext.dll extension error on client connect/disconnect.

However, I was not able to fetch more detailed informations.

I'll comeback again when I have them.

**Comment by Raritylicious** [comment]
Still couldn't get anything.

But one thing is sure.

Server crashes on client Connect and Disconnect with SMRPG.

I tried removing all the other plugins and loaded SMRPG only, still happened. However, Without SMRPG, my server didn't crash.

Plus, not setting "timeout" for smrpg database in databases.cfg didn't make any difference.

**Comment by Raritylicious** [comment]
the problem appears to be the clientprefs related.

**Comment by peace-maker** [comment]
Sorry that i can't help you here :( But crashes in the database layer should be tracked at the sourcemod bug tracker directly.
