### ISSUE TITLE
List of commands 

### ISSUE THREAD

**Issue by blacksteve13** [peace-maker/smrpg#54]
I feel like I'm overlooking something but is there an available list of all the commands associated with this plugin.

I really want to see if there is away to let admins enable and disable turbo mode along with resetting the stats

**Comment by Rownan** [comment]
https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg/smrpg_admincommands.sp

They are all defined in there.

**Comment by peace-maker** [comment]
I've created a [wiki page](https://github.com/peace-maker/smrpg/wiki/Admin-commands) listing the available admin commands.
