### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by PatrykRog** [peace-maker/smrpg#55]
Could u help me install this i have bug when i compiled or anyone can give me smx files ? :C

**Comment by peace-maker** [comment]
What error do you see when compiling? Did you put all the required include files into the scripting/include directory as you were instructed in the readme?

**Comment by PatrykRog** [comment]
Yes but i cant compile files in scripting/smrpg folder :C

**Comment by peace-maker** [comment]
You don't need to. Those files are included in the smrpg.sp core plugin. They are just split out to manage the code. I'll add a note to the readme.
