### ISSUE TITLE
[Minor Bug] Shrinking

### ISSUE THREAD

**Issue by Will-Scarlet** [peace-maker/smrpg#56]
Seems the shrinking command can not be disabled while still alive which is not terrible, but even if you die after disabling shrinking your PoV is still as if you were small. Not a huge deal but thought I would mention it.

**Comment by peace-maker** [comment]
Did you disable the whole upgrade through the admin menu or just disabled it for yourself in the rpgmenu upgrade settings?

**Comment by Will-Scarlet** [comment]
Disabled in the player menu during a round.

**Comment by peace-maker** [comment]
This has been fixed now.
