### ISSUE TITLE
[Major Issue] String Value for Column 'name'

### ISSUE THREAD

**Issue by Will-Scarlet** [peace-maker/smrpg#58]
It seems by default the table created does not support UTF-8 symbols in players names and fails to execute the query to enter them into the database. The exact error received is,

**'Error executing query 2 of 6 queries: Incorrect string value: '\xCC' for column 'name' at row 1'**

**Comment by peace-maker** [comment]
In a mysql database?

**Comment by Will-Scarlet** [comment]
Indeed

**Comment by peace-maker** [comment]
You set the default charset for a database when creating it. Did you select utf8_general_ci as charset when creating your smrpg database?
But you're right, the queries which create the tables don't specify the charset explicitly, but rely on the database being created correctly.
