### ISSUE TITLE
[Minor Issue] Fire Pistols Ignite Effect

### ISSUE THREAD

**Issue by Will-Scarlet** [peace-maker/smrpg#59]
A few errors with the SMRPG_Effects. Occurs from the FirePistols on target hit.

[SM] Native "TriggerTimer" reported: Invalid timer handle 8af907fc (error 3)
[SM] Displaying call stack trace for plugin "custom\smrpg\smrpg_effects.smx":
[SM]   [0]  Line 36, C:\steamcmd\css_surf\cstrike\addons\sourcemod\scripting\smrpg_effects/ignite.sp::ResetIgniteClient()
[SM]   [1]  Line 87, C:\steamcmd\css_surf\cstrike\addons\sourcemod\scripting\smrpg_effects.sp::Event_OnPlayerSpawn()

**Comment by peace-maker** [comment]
Could you update your effects plugin using the latest source and see if you still get those errors?

**Comment by jono666** [comment]
Latest update fixed this issue.
