### ISSUE TITLE
SMRPG CSGO

### ISSUE THREAD

**Issue by PatrykRog** [peace-maker/smrpg#60]
What i must change to working this on CSGO

**Comment by PatrykRog** [comment]
When i say !rpg server crash

**Comment by peace-maker** [comment]
Any errors in the logs?

**Comment by PatrykRog** [comment]
yes
wait

**Comment by Nobody-x** [comment]
Don't use keyhint plugin

**Comment by PatrykRog** [comment]
L 10/12/2015 - 16:59:49: [SM] Native "StartMessage" reported: Unable to execute a new message, there is already one in progress
L 10/12/2015 - 16:59:49: [SM] Displaying call stack trace for plugin "smrpg_keyhint_info.smx":
L 10/12/2015 - 16:59:49: [SM]   [0]  Line 261, C:\Users\dom\Desktop\SERWEROWNIA\sourcemod\scripting\include\usermessages.inc::StartMessageOne()
L 10/12/2015 - 16:59:49: [SM]   [1]  Line 1772, C:\Users\dom\Desktop\SERWEROWNIA\sourcemod\scripting\include\smlib/clients.inc::Client_PrintKeyHintText()
L 10/12/2015 - 16:59:49: [SM]   [2]  Line 164, smrpg_keyhint_info.sp::Timer_ShowInfoPanel()

**Comment by PatrykRog** [comment]
oh dont use this
thanks i will delete

**Comment by PatrykRog** [comment]
Its working thanks a lot friends <33333333 i buy u beer

**Comment by PatrykRog** [comment]
but i dont see upgrades where they are?

**Comment by peace-maker** [comment]
You need to compile the upgrades you want in the scripting/upgrades folder.
