### ISSUE TITLE
CS:S -> "rpgmenu" and "rpg" error

### ISSUE THREAD

**Issue by GB3K** [peace-maker/smrpg#61]
the complete plugin is working with the newest version of sourcemod (leveling, xp gain, credits, ...).
but every time i open the "skill-upgrade-menu" with "rpg" or "rpgmenu" is just popping up an small "admin-"menu to change some rpg server settings

is it possible i have to downgrade sourcemod&metamod to get it work?

best regards

**Comment by peace-maker** [comment]
Uh, could you link a screen shot of the menu you're seeing after typing "rpg"?

**Comment by GB3K** [comment]
![Image of RPGMenu](http://i60.tinypic.com/2vv96j5.png)

Credits: 5
1. Stats
2. Commands
3. Settings

:)

**Comment by Nobody-x** [comment]
It's the RPG menu, but you need to put some skills on your server by
compiling it from upgrades folder.
Le 15 oct. 2015 10:30, "GB3K" <notifications@github.com> a écrit :

[image: Image of RPGMenu]
<https://camo.githubusercontent.com/bffebc8f21fa2fa20d64d4db54f9ed27c5d5a5f5/687474703a2f2f6936302e74696e797069632e636f6d2f32767639366a352e706e67>

Credits: 5
1. Stats
2. Commands
3. Settings

:)

—
Reply to this email directly or view it on GitHub
<https://github.com/peace-maker/smrpg/issues/61#issuecomment-148316927>.

**Comment by GB3K** [comment]
Thanks!
dont saw the folder before xD

now its working like a charm :+1:
