### ISSUE TITLE
No option to change language. Can you help please?

### ISSUE THREAD

**Issue by maxgraham** [peace-maker/smrpg#65]
Hi, i like this plugin, but i have a problem. There is no option where you can change the language, i can see the translation files that there is my country's translation, and its translated, but i need an option to really change it, because in my server there are lots of young person like 12-13, and they don't really know english :/

I tried to look the "rpgmenu_sorting.txt" but i can't understand it, i dont know how to set plugins or write plugins... 

Can you help me please?
Thanks!

**Comment by Nobody-x** [comment]
The language is set by sourcemod un the file config/core.cfg change for
your language

**Comment by maxgraham** [comment]
What if it would be optional? Because i like the english version, i mean its good for me, but for some other player it is  not and i have foregin guests sometimes . Is it possible to add an option for the clients  to choose what they want?

Can i add something to the rpgmenu_sortings that will change the " "ServerLang"	"en" " value? Or it can't be done?

I remember when i played in an RPG server 6 years ago, there was an option in the rpgmenu where i could change the language even to "h4x0r" language, as a normal player and not as an admin.

**Comment by Nobody-x** [comment]
The language is set with the game language. Change your game language.

**Comment by maxgraham** [comment]
Well, then it's not working because i set the game to my own language, even i set Steam to my own language, restarted it, the whole game is on my own language but the rpgmenu still english :/

**Comment by Nobody-x** [comment]
This is an option in sourcemod too

**Comment by maxgraham** [comment]
"The language is set with the game language. Change your game language."

So then it seems it's not changing with the game, what do i have to do Exactly? Tell me please, because i'm getting lost my way...

**Comment by Nobody-x** [comment]
In the core.cfg you have two cvar : ServerLang set With your language and
AllowClLanguageVar set to On

**Comment by maxgraham** [comment]
yea, it's On, but it was On from the beginning as i see, so not this is the problem. I don't know if you have free time, but can you look up for yourself? I mean just to see if it works for you, because if not, then there is a bug/problem, that should be fixed, but if it's working for you then i don't have a clue becuase i set and copied everything, and i did what you said :/

**Comment by Nobody-x** [comment]
I've a french and english server, then in both i see the RPG in french but
others like english spanish german peoples see it in their language

**Comment by maxgraham** [comment]
can you please tell me the IP? I will go there and see if it shows my language

**Comment by peace-maker** [comment]
Check if your addons/sourcemod/configs/languages.cfg file contains more languages than just english. There's been problems in the recent past with release versions not containing the correct languages files. Replace it with a languages.cfg from a new sourcemod release package.

**Comment by maxgraham** [comment]
Oh my god thank you! Now its working, but its just half-translated, i tried to translate the rest but there are still parts that i can't translate because there is no english translation file, for example i can translate the "Commands" title, but inside the commands i can't translate what command what does. Are there any way? 

And by the way i saw many upgrade like Poison Smoke,fast reload,Shrinking that doesn't exist, its an upcoming feature or its just deleted? Because i saw its CS:S only, but can you port it to CS:GO?

Thanks you! And thanks for the awesome plugin!

**Comment by peace-maker** [comment]
Which language are you looking at? You should have a look at the base english phrases files. I didn't add new phrases to all languages when i added them. I'd gladly merge your translations!
Could you describe exactly which strings in smrpg aren't translatable? The smrpg admin menu is english only.

I didn't come around to implement these features in csgo. Shrinking isn't possible, because of the way player models are structured in csgo. m_flModelScale doesn't apply to all bones and just resizes some which destroys all proportions.

**Comment by maxgraham** [comment]
Well i looked for the Hungarian translation files, i added the new skill's translation like Armor+ and the others... that were not translated, and what i want to translate but i cant is the "command" menu (or the help?) that are not for admins, it's the explaination for the players what can they do with commands like "rpgtop10 -> shows the top players" or "rpgsession -> shows your current rank" this is what i want to translate but i can't find the translation file for these.

After i finished i can send you my translations if you want, but first i want to do these (if it is possible)

**Comment by peace-maker** [comment]
They're in the main phrases file.
https://github.com/peace-maker/smrpg/blob/master/translations/smrpg.phrases.txt#L340

**Comment by maxgraham** [comment]
Thank you!

I think i finished with the Hungarian translation, i translated the missing parts

http://www.2shared.com/file/0aOqQK0j/smrpg_hun_translation_extended.html

if you want them

**Comment by peace-maker** [comment]
Thank you a lot!
I've added them to the repository.
