### ISSUE TITLE
Randomly rejoin my server, reset to level 1?

### ISSUE THREAD

**Issue by whocodes** [peace-maker/smrpg#66]
Been testing a new server setup on CS:GO and have had myself at level 100 for about 2 weeks of testing; no issues. I rejoin during testing today and my row in SQL is reset with default statistics?

In fact, the SQL row is even updated with a lastreset timestamp that ends up being about 10 minutes ago.

Plugins: http://i.imgur.com/tDPTwdN.png

I did in-fact have it set to delete inactive players after a day, but I can't think of a scenario where I'm in-game at level 100 and rejoin to become level 1 (0 disables expiry deletion, 1 is a day... where's the in-between). 

Perhaps maybe my stats were loaded asynchronously at around the same time the expired players were being deleted? My point is that it shouldn't be possible.

**Comment by peace-maker** [comment]
Hm, you don't run the resetstats plugin? This is really odd. The database is cleaned of old players when it first connects and at each map start. The player stats are saved at an interval, at map end and on player disconnect.

Your stats should have been saved and the lastseen timestamp updated before the player expiry query ran.

Do you remember when you rejoined? Did you just did a "retry" or could there been a map change in the meantime?
