### ISSUE TITLE
Compiling.

### ISSUE THREAD

**Issue by coffeefrea** [peace-maker/smrpg#69]
I cant compile it in any 1.6 version of sourcemod. the autoexecconfig.inc has to many error. could you please help?

**Comment by Nobody-x** [comment]
You need sm 1.7

**Comment by coffeefrea** [comment]
scripting\include\autoexecconfig.inc(92) : error 010: invalid function or declaration
smrpg/smrpg_upgrades.sp(190) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_upgrades.sp(367) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_upgrades.sp(514) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_players.sp(329) : error 017: undefined symbol "ClearHandle"
smrpg/smrpg_stats.sp(702) : error 017: undefined symbol "ClearHandle"
smrpg.sp(144) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg.sp(290) : error 017: undefined symbol "ClearHandle"
smrpg.sp(350) : error 017: undefined symbol "ClearHandle"

**Comment by coffeefrea** [comment]
scripting\include\autoexecconfig.inc(92) : error 010: invalid function or declaration
smrpg/smrpg_upgrades.sp(190) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_upgrades.sp(367) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_upgrades.sp(514) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg/smrpg_players.sp(329) : error 017: undefined symbol "ClearHandle"
smrpg/smrpg_stats.sp(702) : error 017: undefined symbol "ClearHandle"
smrpg.sp(144) : error 017: undefined symbol "AutoExecConfig_SetCreateFile"
smrpg.sp(290) : error 017: undefined symbol "ClearHandle"
smrpg.sp(350) : error 017: undefined symbol "ClearHandle"

ye still get lot of errors

**Comment by peace-maker** [comment]
Did you use the versions of autoexecconfig and smlib from github? The packages attached to the release posts in the forum can be outdated.

**Comment by coffeefrea** [comment]
I did. i try only those from github :S

**Comment by peace-maker** [comment]
Well, check again because they're both there. [ClearHandle](https://github.com/bcserv/smlib/blob/master/scripting/include/smlib/general.inc#L245) and [AutoExecConfig_SetCreateFile](https://github.com/Impact123/AutoExecConfig/blob/master/autoexecconfig.inc#L93).
