### ISSUE TITLE
Problems compiling several parts.

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#70]
//// smrpg_database.sp
//
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(126) : error 017: undefined symbol "LoadSettingsTable"
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(130) : error 017: undefined symbol "GetUpgradeCount"
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(131) : error 017: undefined symbol "InternalUpgradeInfo"
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(131) : error 009: invalid array size (negative, zero or out of bounds)
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(131) : error 036: empty statement
// C:\Users\Kristaps\Desktop\scripting\smrpg_database.sp(131) : fatal error 190: too many error messages on one line

Using newest SM Dev release.

Having trouble compile also:
admincommands.sp
players.sp
menu.sp

It looks like I can't compile anything within the smrpg folder.
Getting seperate errors on each one.

**Comment by Hetachi** [comment]
I am quite dumb, once I read the smrpg.sp, I realised that they are not meant to be compiled seperately and are just includes for main plugin...

**Comment by peace-maker** [comment]
As stated right in the second point of the [install instructions](https://github.com/peace-maker/smrpg#installation). :smile:
