### ISSUE TITLE
RPG Upgrade not accepting input 1.00?

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#72]
I changed the values in RPG script to 1.00 which should mean 100% ?

But instead it seems that the script does not work at all, or do I have to somehow clear the cache of something? As I have tried restarting the server, but it simply doesn't have any effect as it seems, no errors too as far as I can tell.

**Comment by peace-maker** [comment]
I have a hard time guessing which file and value you changed or what you're trying to do. Usually i'm acceptable with mind reading, but you seem to fail me :(

**Comment by Hetachi** [comment]
Yea I thought I should have added the code part too, but it was quite late :D 

anyway without further a due my code:

public OnLibraryAdded(const String:name[])
{
	// Register this upgrade in SM:RPG
	if(StrEqual(name, "smrpg"))
	{
		SMRPG_RegisterUpgradeType("Long Jump", UPGRADE_SHORTNAME, "Boosts your jump speed.", 10, true, 5, 20, 15, _, SMRPG_BuySell, SMRPG_ActiveQuery);
		SMRPG_SetUpgradeTranslationCallback(UPGRADE_SHORTNAME, SMRPG_TranslateUpgrade);
		
		g_hCVIncrease = SMRPG_CreateUpgradeConVar(UPGRADE_SHORTNAME, "smrpg_ljump_inc", "1.00", "Percent of player's jump distance to increase per level.", 0, true, 0.01);
		g_hCVIncreaseStart = SMRPG_CreateUpgradeConVar(UPGRADE_SHORTNAME, "smrpg_ljump_incstart", "1.00", "Percent of player's initial jump distance to increase per level.", 0, true, 0.01);
	}
}
 
What I changed: 
SMRPG_RegisterUpgradeType("Long Jump", UPGRADE_SHORTNAME, "Boosts your jump speed.", 10, true, 5, 20, 15, _, SMRPG_BuySell, SMRPG_ActiveQuery);

after description as I understood:
10 = Hardcoded Max levels
5 = max level
20 = Starting cost
15 = Cost incremental 

and also I edited 
"smrpg_ljump_inc", "1.00", 

as the 1.00 was 0.10 I assumed that 0.10 = 10% and 1.00 should be 100%

**Comment by peace-maker** [comment]
You shouldn't edit the source code to change those values. There is a config file generated in `[mod]/cfg/sourcemod/smrpg/smrpg_upgrade_longjump.cfg` with convars for all the values who's defaults are set in `SMRPG_RegisterUpgradeType` and `SMRPG_CreateUpgradeConvar`.

(As stated in [the documentation](https://github.com/peace-maker/smrpg/blob/master/scripting/include/smrpg/smrpg_upgrades.inc#L46) you seem to have partially read :P)

**Comment by Hetachi** [comment]
I am now kind of scared to write anything else, gonna read the documentation 3 times....
