### ISSUE TITLE
MYSQL errors (Detailed Errorlog file included)

### ISSUE THREAD

**Issue by Raritylicious** [peace-maker/smrpg#73]
[errors.txt](https://github.com/peace-maker/smrpg/files/51390/errors.txt)

it literally spammed 4gb size of errors so i had to chunk it down to upload it here.

It appears to happens whenever the server loses connection with mysql host or the host is offline.
And eventually, crashed the server.

**Comment by Hetachi** [comment]
I would suggest for you to remove the address of your mysql db, as it might be used to hurt your services.

**Comment by peace-maker** [comment]
See #26 
This was fixed in sourcemod 1.8.
It will just unload all dependent plugins if the core fails to load due to a failed database connection.

This wasn't merged into sourcemod 1.7 yet (since january), so there isn't much we can do here except upgrading to sourcemod 1.8 :(
