### ISSUE TITLE
Steam id that is saved to MYSQL

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#74]
Simple question steam id which is saved to mysql db in players table is steamdid3 ? 
Which full version would be [U:1:197323781] ?

**Comment by Nobody-x** [comment]
The saved data innthe table is the third part of the steamId3
([U:1:thispart]) the steamId 2 can be converted to this part with an easy
equation. (Check the RPG migration source code)

**Comment by Hetachi** [comment]
Alright thanks, just wanted to be sure.
