### ISSUE TITLE
Static exp income

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#75]
Even by setting:```
g_hCVExpDamage = AutoExecConfig_CreateConVar("smrpg_exp_damage", "0", "Experience for hurting an enemy multiplied by the damage done", 0, true, 0.0);```

To 0 it still adds dmg as xp gained, and people can farm the expirience within the server indefinetly by simply using knife and hp regen.

**Comment by peace-maker** [comment]
You shouldn't edit the source code to change those values. There is a config file generated in `[mod]/cfg/sourcemod/plugin.smrpg.cfg`.
Have a look at the `[mod]/addons/sourcemod/configs/smrpg/weapon_experience.cfg` as well to disable special experience values for the knife.
