### ISSUE TITLE
Can't find the smx file?

### ISSUE THREAD

**Issue by freaky1** [peace-maker/smrpg#78]
I always have trouble adding RPG to my servers. it never works :/ 
dropped all the files into my Sourcemod and then it says drop the smx file into plugins but i don't know where it is?

**Comment by Nobody-x** [comment]
You need to compile all needed files in the scripting directory and all
needed upgrades in the scripting/upgrades directory.

**Comment by freaky1** [comment]
by compile do you mean just drag the files into my server or how do you do that? Sorry for asking such a noob question but I appreciate your help!

**Comment by Nobody-x** [comment]
No problem it's not a noob question. You need to dowload sourcemod for your
OS (if you're running on windows get the windows version). Note It's only
to compile scripts. Not to put This source mod on your server. Then dowload
as mentioned in the readme all smlib inc files and dhook inc files. Place
them in your downloaded source mode scripting directory with smrpg files.
Then just drag and drops smrpg's ".sp" files on "compile.exe". Note that
you need sourcemod 1.7 or more to compile and run this plugin.

**Comment by Nobody-x** [comment]
All compiled files should be in the "compiled" folder

**Comment by freaky1** [comment]
Okay, i already have sourcemod which is higher than 1.7 and i did what you said by compiling them to the compile.exe file. Then i dragged them all into the compiled folder as you said? but then when i launch my server nothing happens? :/ 

Can you add me on steam by any chance, i think it would be faster there maybe - Btw thank you a lot for your help!

**Comment by Nobody-x** [comment]
After compiling smx files appear in the sourcemod/scripting/compiled
folder, but You need to put them in the sourcemod/plugins folder of
sourcemod (server side)

**Comment by freaky1** [comment]
Okay so now i did that and yet it wont starup rpg :/ ;y console is saying this, don't know if it's any help


L 12/10/2015 - 10:46:41: server_cvar: "sm_nextmap" "surf_greatriver_2015"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_antisuicide.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_chatxpstats.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_commandlist.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_disablexp.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_gifting.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_turbomode.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_antidote.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_armorplus_cstrike.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_armorregen_cstrike.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_bouncybullets.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_clipsize.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_damage.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_denial.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_firepistol.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_firerate.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_fnade.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_fpistol.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_gravity.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_grenaderesup_cstrike.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_health.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_icenade.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_icestab.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_impulse.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_ljump.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_medic.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_regen.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_resup.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_stealth.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:41: [SM] Unable to load plugin "smrpg_upgrade_vampire.smx": Could not find required plugin "smrpg"
L 12/10/2015 - 10:46:42: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 12/10/2015 - 10:46:44: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 12/10/2015 - 10:46:45: [admin-sql-prefetch.smx] Could not connect to database "default": [2003]: Can't connect to MySQL server on 'localhost' (10061)
GameTypes: missing, < 1, or invalid maxplayers entry for game type/mode (classic/casual).

**Comment by Nobody-x** [comment]
Wich game is CS:S or CS:GO ? Have you compiled smrpg.smx? Have you
configured the database settings ?

**Comment by freaky1** [comment]
Im using CS:GO - i don't have the smrpg.smx only .sp and when i try to compile it, it just says (fatal error 182: couldn't read from file: "autoexecconfig")

I haven't changed the database settings, no because i copied what it said in the instructions but it was already there in the databases.cfg file?

**Comment by Nobody-x** [comment]
Yes sorry i forgot the autoexecconfig lib, you need it (link in the readme
with dhook and smlib) dowload the inc file and put it in your scripting
directory to compile smrpg. After that put smrpg.smx in the server.

**Comment by Nobody-x** [comment]
the autoexecconfig inc goes in scripting/include

**Comment by freaky1** [comment]
OMG I GOT IT!!!!!! :D 

Thank you so much for your help and patience! hopefully this will thread will help others as well :) 
thank you, thank you, thank you!!!!

**Comment by Nobody-x** [comment]
Yes after the plugin has been executed for the first time, you have the configs files in cfg/sourcemod.
