### ISSUE TITLE
please add support for new csgo pistol

### ISSUE THREAD

**Issue by PresidentEvil** [peace-maker/smrpg#79]
weapon_revolver

**Comment by peace-maker** [comment]
where? what's not working?

**Comment by tellekx3** [comment]
When you have denial upgrade and you re using revolver instead of deagle after you die denial gives you deagle instead of revolver :D

**Comment by PresidentEvil** [comment]
oh you're right peace maker, it does work, I should have checked (i remember in THC-RPG new guns needed to be updated in the plugin, but i guess this plugin does it automatically)

**Comment by peace-maker** [comment]
Seems to be the same as #29
