### ISSUE TITLE
Max lvls

### ISSUE THREAD

**Issue by oliersej** [peace-maker/smrpg#8]
For most upgrades the configs dont work.
So when you change something they are still at the default.
One that is working is firerate, almost every other dont work.
Pretty sure I setup everything correctly.

**Comment by peace-maker** [comment]
Just type the convar without any value like "smrpg_health_maxlevel"

**Comment by oliersej** [comment]
Output:
"smrpg_health_maxlevel" = "1000" ( def. "16" ) min. 1.000000
- Health+ upgrade maximum level. This is the maximum level players can reach for this upgrade.
When changed, all players who bought a higher level before are refunded with the full upgrade costs and set down to the new maxlevel. 

But still the max lvl is the default lvl "16".

**Comment by peace-maker** [comment]
Can you confirm, the maxlevel is set correctly through the adminmenu?
The above change fixes showing wrong values for the maxlevel convar, if the value was capped. You could try the newest version and check again, if the maxlevel is correctly changed.

Could you also confirm that smrpg_ignore_level_barrier is set to 1 the same way as you did with the health_maxlevel convar?

**Comment by oliersej** [comment]
Sure:
"smrpg_ignore_level_barrier" = "1" ( def. "0" ) min. 0.000000 max. 1.000000
- Ignore the hardcoded maxlevels for the upgrades and allow to set the maxlevel as high as you want. THIS MIGHT BE BAD!

For some reason after the update, more of the upgrades are working.
But still there is 10+ not working.

**Comment by oliersej** [comment]
Got it working, no idea how.
Did a couple of restarts and added som new plugins, but now its working.

Btw in the rpgmenu under upgrade settings, its also showing the default value.

And many thanks for the support, and for the great plugin, thanks.

**Comment by peace-maker** [comment]
The level displayed under upgrade settings is the current purchased level of the player, not the maximal possible level of the upgrade.
