### ISSUE TITLE
[Request] Seperate plugin, as extension for double xp weekends and switch for admin panel

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#80]
Any possibility that anyone could make an extension to the rpg which would allow from admin panel double the exp gained? and disable it as well?

**Comment by peace-maker** [comment]
You basically only need to do something like
https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg_turbomode.sp#L241

And use [SMRPG_GetSetting](https://github.com/peace-maker/smrpg/blob/master/scripting/include/smrpg/smrpg_settings.inc#L16) to check for some setting you could change from some admin panel.

You should cache the setting value on map start or refresh the cache like every 5 minutes to prevent query spam.
