### ISSUE TITLE
[Problem] Is there any way to put rpg menu infront of money?

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#81]
Since money is blocking the view of rpg panel, is there any way to force it on top of the money?

**Comment by peace-maker** [comment]
One could hide the money, while the RPG menu is open. Don't know how easy that can be done reliably.

**Comment by whocodes** [comment]
If you're using this alongside deathmatch then you can set mp_maxmoney to 0 and it will disappear.

**Comment by Hetachi** [comment]
well one way would be to cache the money player has and set it to 0, afterwards set the money back to the amount they had before opening menu. But the question is how much resources this kind of operation would require?

**Comment by peace-maker** [comment]
You'll need more logic to handle changes to the money while the menu is open.

**Comment by Hetachi** [comment]
Okay, well atm I will close this issue, as I don't think that it's that annoying, and I think the hassle wouldn't be worth it.
