### ISSUE TITLE
[Minor] Changing one skills language? (Reduced Gravity)

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#83]
latest stable sm/mm:s and smrpg. CS:S.
I cannot figure out how to change the language of the gravity skill. It shows as Gravitacio csokkentes. All other skills are in english, including the gravity skill description. I looked in the smrpg_stock_upgrades.phrases.txt but it's set as english. How can i change it?

**Comment by Nobody-x** [comment]
You can see in the hu/smrpg_stock_upgrades.phrases.txt an "en" tag instead of "hu" tag.
