### ISSUE TITLE
armor plus problem

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#85]
Auto ganerated config smrpg_upgrade_armorplus.cfg dont control cvars.
I made smrpg_armorplus_maxlevel "12" and smrpg_armor_inc "25"
but i have only 127 points of Armor.
I think this file of config dont control cvars of Armor settings

**Comment by coty9090** [comment]
127 Armor is the max you can set it.

**Comment by peace-maker** [comment]
The armor value is only a signed byte, so you can't set it higher than 127. It would overflow and display as negative number, which is why I've capped it at 127 in the upgrade.
