### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#86]
I have full russian translation. I made this translation two days ago.
I can send you.

**Comment by Bara20** [comment]
Create a [Pull Request](https://github.com/peace-maker/smrpg/pulls) for this.

**Comment by peace-maker** [comment]
If you don't know how to create a pull request, it's fine to just upload it somewhere and link it here too :) Thank you for your time

**Comment by peace-maker** [comment]
@vBDSK feel free to send it in, if you find the time. Closing this for now, as it's no request i can fulfill on my own.
