### ISSUE TITLE
How about !rpgadmin

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#87]
How about made special menu for admins.
I think the menu item in the admin panel its not OK for admins, who is selling admin access

**Comment by Hetachi** [comment]
There is an admin panel, you just need ADMIN_FLAG "Z" to access it, if you are using sourcemod.

**Comment by peace-maker** [comment]
I could add a command to open the smrpg admin menu directly, skipping the sm_admin menu and just displaying the topmenu category directly. That could already be enough for you?

We'd need to test, if you're able to open categories directly, even if you don't have access to the root topmenu. Or if you're able to go "back" to it after going to the category directly.

There are overrides available to manage the access to the menu items:
`smrpg_adminmenu` controls whether the whole SM:RPG admin menu section is available.
`smrpg_players_menu` controls whether the "Manage players" item is available
`smrpg_upgrades_menu` controls whether the "Manage upgrades" item is available
They all default to the `config (i)` flag.

**Comment by peace-maker** [comment]
When adding a sm_rpgadmin command which opens SM:RPG's adminmenu category directly, there always is a "Back" button to go back to the root adminmenu opened by "sm_admin".
So admins could access the !admin menu even if they don't have access to the sm_admin command :(

Well, i'll add the short cut anyways.
