### ISSUE TITLE
cant make it work?

### ISSUE THREAD

**Issue by maxcash123** [peace-maker/smrpg#88]
Ì've just putted all the files in Sourcemod, can't figure out why it wont work? can you make a better installing instructions? I would love you if you could :)

**Comment by coty9090** [comment]
Read ALL of the instructions.

**Comment by maxcash123** [comment]
yes, but I don't really understand it, sorry :(

Date: Fri, 25 Dec 2015 11:45:17 -0800

**Comment by peace-maker** [comment]
You need to compile the plugins and put the generated .smx files on your server. See #78
