### ISSUE TITLE
Upgrades menu not showing up

### ISSUE THREAD

**Issue by Deven95** [peace-maker/smrpg#9]
when i type rpgmenu only stats/commands/settings show there is no upgrades or sell, ect i've compiled it all properly i have it hooked up through mysql i did my database.cfg correctly i can see i was created in phpmyadmin but i can't see the upgrades menu just doesnt show up at all i've tryed on 2 servers

**Comment by jono666** [comment]
Please provide more information

What game
What version of sourcemod are you running on your server
What version of sourcemod did you compile smrpg with
Have you looked at error logs

etc

**Comment by jono666** [comment]
Are you sure you compiled the .sp files for upgrades?
Copy the .sp files from the upgrades folder into the scripting folder and compile.
