### ISSUE TITLE
New idea for ADMINS of RPG servers

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#90]
I think its good function.
You can give key to players and they can use this keys in console.
For example, Player want to buy 1000 credits and he pay. Next, you give him special key(for example Testkey-1000) and he types in the console this key and he get 1000 credits.
Author its is very intresting function for donate

**Comment by peace-maker** [comment]
You're better of doing it yourself, i won't include such pay-to-win stuff it in this repository.

I'd do it using a database where you generate a hash and pair it with the amount of credits it's worth when a player wants to buy credits.
Ingame add a command like "sm_rpgredeem <hashcode>" and check the database for a coupon with this hash, see if it's still valid and wasn't redeemed before and add the amount of credits specified in the database using [SMRPG_SetClientCredits](https://github.com/peace-maker/smrpg/blob/master/scripting/include/smrpg/smrpg_clients.inc#L44).

**Comment by vBDSK** [comment]
Speaking about my idea, can you make special plugin for me and I pay for you

**Comment by Hetachi** [comment]
Just a noted to anyone who wants to make RPG pay-to-win based, use XP instead of credits, as XP values increase the price per level does too, that way new players will be more tempted to buy the xp, in order to catch up with the higher level players, as they also would gain more from it, than for example level 200 player.

**Comment by Nobody-x** [comment]
My servers use the 1 Kill = 1 level system. So give xp or credit is the
same but when you buy xp your level increase. When you buy credits. You're
still low level. So you dont fuck the rank system.
