### ISSUE TITLE
[Request] Separate smrpg_addexp from earn exp

### ISSUE THREAD

**Issue by Dropsuuu** [peace-maker/smrpg#92]
I Write "Exp x2" plugin basing on smrpg_turbomode.sp and if i give someone 1000 exp by command smrpg_addexp when exp x2 is enable he recives 2000 exp.

piece of code which add exp x2:
public Action:SMRPG_OnAddExperience(client, const String:reason[], &iExperience, other)
{
	iExperience = RoundToCeil(float(iExperience) * 2.0;
}

If in the code i have "iExperience = RoundToCeil(float(iExperience) * 1.0;"
command smrpg_addexp working as it should.

I do not want to change anything in your smrpg code because from time to time you update it. But if I can change something in your plugin to it worked I listen to suggestions. Generally it would be good if you could just separated at the next update.

And sorry for my English :<.

**Comment by peace-maker** [comment]
You have to check the reason. All the admin commands use the `ExperienceReason_Admin` string as reason, so you only need to apply your changes if the reason is different.
Like it's done in the turbomode plugin.

https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg_turbomode.sp#L246
