### ISSUE TITLE
[Problem] Spam in error log if MySQL database temporary is shut down

### ISSUE THREAD

**Issue by Dropsuuu** [peace-maker/smrpg#95]
If database temporary is shut down i have after 20 minutes error log which has over 300mb!
There are over 4000 entites of error per second!
Can you improve it / fix it please?

errors which mostly are repeated:

L 01/27/2016 - 11:17:33: [SM] Native "SMRPG_IsEnabled" reported: Plugin owning this native is currently paused.
L 01/27/2016 - 11:17:33: [SM] Displaying call stack trace for plugin "smrpg/rpgupgrade/smrpg_upgrade_speed.smx":
L 01/27/2016 - 11:17:33: [SM]   [0]  Line 106, smrpg_upgrade_speed.sp::Hook_GetPlayerMaxSpeedPost()

L 01/27/2016 - 11:17:33: [SM] Native "SMRPG_IsEnabled" reported: Plugin owning this native is currently paused.
L 01/27/2016 - 11:17:33: [SM] Displaying call stack trace for plugin "smrpg/rpgupgrade/smrpg_upgrade_gravity.smx":
L 01/27/2016 - 11:17:33: [SM]   [0]  Line 187, smrpg_upgrade_gravity.sp::ApplyGravity()
L 01/27/2016 - 11:17:33: [SM]   [1]  Line 96, smrpg_upgrade_gravity.sp::Hook_OnClientPostThinkPost()

L 01/27/2016 - 11:17:32: [SM] Native "SMRPG_IsEnabled" reported: Plugin owning this native is currently paused.
L 01/27/2016 - 11:17:32: [SM] Displaying call stack trace for plugin "smrpg/rpgupgrade/smrpg_upgrade_ljump.smx":
L 01/27/2016 - 11:17:32: [SM]   [0]  Line 139, smrpg_upgrade_ljump.sp::LJump_HasJumped()
L 01/27/2016 - 11:17:32: [SM]   [1]  Line 116, smrpg_upgrade_ljump.sp::OnPlayerRunCmd()

**Comment by peace-maker** [comment]
This is a bug in sourcemod :disappointed: See #73 
I'll try to work around it, by just not calling SetFailState, if the database fails to connect.

**Comment by peace-maker** [comment]
This should now only occur, if there are more serious problems with the database, than a failed connection on load.
