### ISSUE TITLE
Spam rpginfo and server lags

### ISSUE THREAD

**Issue by vBDSK** [peace-maker/smrpg#96]
Players can spam using command rpginfo. They bind this command and spam. I have lags on my server

**Comment by peace-maker** [comment]
We should add a rate limit on all commands then, not only the rpginfo one.

**Comment by vBDSK** [comment]
how can i add?

**Comment by peace-maker** [comment]
Are you sure you're talking about the `rpginfo` command? It's the one which opens a menu with the upgrade levels of the target player.

I've fixed some hidden chat spam problem with the `rpgrank` command in 120a75a3f6456dad7d9149b66bacb97495efa7c1
