### ISSUE TITLE
problem with compile

### ISSUE THREAD

**Issue by benne-zz** [peace-maker/smrpg#97]
hello. i though i got everything working. But as me and some freinds started to play on the server. no upgrades where working. We can upgrade them and all. but nothing happens. upgraded all full and still no longjump / hp  and so on. so i though i would try it all again (because im a huge noob with this compile thing) and i notice that one upgrade give this error. Can it be something with that?

ps. sorry for my english. I hope you understand it anyways 
![problem](https://cloud.githubusercontent.com/assets/389857/12875149/1726b1ea-cde4-11e5-823a-c35694ed8f74.png)

**Comment by benne-zz** [comment]
i got alot of errors now. like this one 
![latterligt](https://cloud.githubusercontent.com/assets/389857/12875430/89c45d96-cdea-11e5-8952-dc9d35f49c74.png)

**Comment by peace-maker** [comment]
You're missing the [Dhooks](https://forums.alliedmods.net/showthread.php?t=180114) include in your scripting/includes folder for the speed upgrade to compile. You'll need the dhooks extension running on your server as well.

You only have to compile the plugins in the root smrpg scripting folder and the scripting/upgrades folder. All other files in the other subdirectories are included by one of the plugins. Like the smrpg.sp including the smrpg/smrpg_stats.sp etc. So don't try to compile those on their own.

Are there any errors in the sourcemod logs when buying the upgrades and not having them work? It could be some problem with other plugins interfering as well.

**Comment by benne-zz** [comment]
No errors in the logs about upgrades. But im gonna try it All again when i get home from work. Thanks for the answer.

**Comment by benne-zz** [comment]
Oh i forgot That i have dm plugin installed. Maybe That Can cause some problems. But im gonna try it All on a fresh server. Cause i got wcgo on the server when i started it. But deleted it again. But maybe not everything is deleted from That plugin

**Comment by benne-zz** [comment]
YES!!!. its working now. I think there was something left with the wcgo ranking system. So it messed up the rpg rank. Thank you the the help!!
