### ISSUE TITLE
[Issue] Weird Text?

### ISSUE THREAD

**Issue by nomorholywar** [peace-maker/smrpg#99]
Hi,

After following the instructions on [#this](https://github.com/peace-maker/smrpg/issues/78), & ofc https://github.com/peace-maker/smrpg, i compiled the plugins, and added them along with the Compile requirements. 
I also added:
`    "smrpg"
    {
        "driver"            "sqlite"
        "database"          "smrpg"
    }`
to the databases.cfg

Now, for some reason the rpgmenu prints out this text for me: http://i.imgur.com/3ukvxRA.jpg
And the whole menu is like that, exept TAB2, which shows: http://i.imgur.com/pF2tuDt.jpg and prints out what i click in the chat.

What did i do wrong? Thanks.
http://steamcommunity.com/id/Koga73

**Comment by peace-maker** [comment]
Strange, make sure smrpg's translation files are all uploaded correctly. There even is an old basic danish phrases file, which should translate parts of the menu.

**Comment by nomorholywar** [comment]
Hi,

My server should mainly use the english translation, even though my game doesn't.


This might be the problem though:

I added SourceMod, along with the compile requirements & the smrpg on my OS.
After that, i compiled these .sp files:

> smrpg
> smrpg_antisuicide
> smrpg_chatxpstats
> smrpg_commandlist
> smrpg_cstrike
> smrpg_disablexp
> smrpg_effects
> smrpg_gifting
> smrpg_import_thcrpg
> smrpg_keyhint_info
> smrpg_resetstats
> smrpg_turbomode

Now, after this, i added them to the plugin folder, and copied the whole sourcemod folder, and pasted it into my server, and overwrote the already existing sourcemod with the new files that was on my OS (the files mentioned above).
Shouldn't i have done that? Did i forget to compile anything?
Thank you, i hope this made any sense.

**Comment by peace-maker** [comment]
Overwriting the files was fine. The plugin package doesn't overwrite any existing sourcemod files.
You compiled some upgrades as well, right? This wouldn't be related though.

Are other translateable sourcemod menus and messages displaying correctly? Have reuploaded the translation phrases? Does the rpgadmin menu show up correctly?

**Comment by nomorholywar** [comment]
Where are the upgrades? I have only compiled the files shown above.

Looks like the rest of the menu is fixed now, it was the translateable files, thanks!
http://i.imgur.com/3geREBj.jpg

**Comment by nomorholywar** [comment]
Oh wow, i found it.. Thank you for helping me

**Comment by peace-maker** [comment]
Glad you solved it. Just for completion - no don't compile the files in **scripting/smrpg**, but compile the upgrades you want in **scripting/upgrades**.

If you happen to translate the missing phrases from the english translation files to danish, i'd be happy to include it here :smile:
